<?php

namespace Database\Seeders;

use App\Models\Municipality;
use App\Models\ZipCode;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class AguasCalientesZipCodesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $zipCodes = [
            [ 'zip_code' => '20000', 'locality' => 'Aguascalientes', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20010', 'locality' => 'Aguascalientes', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20016', 'locality' => 'Aguascalientes', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20018', 'locality' => 'Aguascalientes', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20020', 'locality' => 'Aguascalientes', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20029', 'locality' => 'Aguascalientes', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20030', 'locality' => 'Aguascalientes', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20040', 'locality' => 'Aguascalientes', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20049', 'locality' => 'Aguascalientes', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20050', 'locality' => 'Aguascalientes', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20059', 'locality' => 'Aguascalientes', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20060', 'locality' => 'Aguascalientes', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20064', 'locality' => 'Aguascalientes', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20070', 'locality' => 'Aguascalientes', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20078', 'locality' => 'Aguascalientes', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20080', 'locality' => 'Aguascalientes', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20089', 'locality' => 'Aguascalientes', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20100', 'locality' => 'Aguascalientes', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20110', 'locality' => 'Aguascalientes', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20115', 'locality' => 'Aguascalientes', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20116', 'locality' => 'Aguascalientes', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20117', 'locality' => 'Aguascalientes', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20118', 'locality' => 'Aguascalientes', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20119', 'locality' => 'Aguascalientes', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20120', 'locality' => 'Aguascalientes', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20123', 'locality' => 'Aguascalientes', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20124', 'locality' => 'Aguascalientes', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20126', 'locality' => 'Aguascalientes', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20127', 'locality' => 'Aguascalientes', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20128', 'locality' => 'Aguascalientes', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20129', 'locality' => 'Aguascalientes', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20130', 'locality' => 'Aguascalientes', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20135', 'locality' => 'Aguascalientes', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20136', 'locality' => 'Aguascalientes', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20137', 'locality' => 'Aguascalientes', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20138', 'locality' => 'Aguascalientes', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20140', 'locality' => 'Aguascalientes', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20146', 'locality' => 'Aguascalientes', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20149', 'locality' => 'Aguascalientes', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20150', 'locality' => 'Aguascalientes', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20157', 'locality' => 'Aguascalientes', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20158', 'locality' => 'Aguascalientes', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20159', 'locality' => 'Aguascalientes', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20160', 'locality' => 'Aguascalientes', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20164', 'locality' => 'Aguascalientes', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20169', 'locality' => 'Aguascalientes', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20170', 'locality' => 'Aguascalientes', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20172', 'locality' => 'Aguascalientes', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20174', 'locality' => 'Aguascalientes', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20175', 'locality' => 'Aguascalientes', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20177', 'locality' => 'Aguascalientes', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20179', 'locality' => 'Aguascalientes', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20180', 'locality' => 'Aguascalientes', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20190', 'locality' => 'Aguascalientes', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20196', 'locality' => 'Aguascalientes', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20198', 'locality' => 'Aguascalientes', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20199', 'locality' => 'Aguascalientes', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20200', 'locality' => 'Aguascalientes', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20205', 'locality' => 'Aguascalientes', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20206', 'locality' => 'Aguascalientes', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20207', 'locality' => 'Aguascalientes', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20208', 'locality' => 'Aguascalientes', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20210', 'locality' => 'Aguascalientes', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20216', 'locality' => 'Aguascalientes', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20217', 'locality' => 'Aguascalientes', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20218', 'locality' => 'Aguascalientes', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20219', 'locality' => 'Aguascalientes', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20220', 'locality' => 'Aguascalientes', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20229', 'locality' => 'Aguascalientes', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20230', 'locality' => 'Aguascalientes', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20234', 'locality' => 'Aguascalientes', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20235', 'locality' => 'Aguascalientes', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20236', 'locality' => 'Aguascalientes', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20237', 'locality' => 'Aguascalientes', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20238', 'locality' => 'Aguascalientes', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20239', 'locality' => 'Aguascalientes', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20240', 'locality' => 'Aguascalientes', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20247', 'locality' => 'Aguascalientes', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20248', 'locality' => 'Aguascalientes', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20249', 'locality' => 'Aguascalientes', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20250', 'locality' => 'Aguascalientes', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20255', 'locality' => 'Aguascalientes', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20256', 'locality' => 'Aguascalientes', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20257', 'locality' => 'Aguascalientes', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20259', 'locality' => 'Aguascalientes', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20260', 'locality' => 'Aguascalientes', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20263', 'locality' => 'Aguascalientes', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20264', 'locality' => 'Aguascalientes', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20265', 'locality' => 'Aguascalientes', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20266', 'locality' => 'Aguascalientes', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20267', 'locality' => 'Aguascalientes', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20268', 'locality' => 'Aguascalientes', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20269', 'locality' => 'Aguascalientes', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20270', 'locality' => 'Aguascalientes', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20276', 'locality' => 'Aguascalientes', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20277', 'locality' => 'Aguascalientes', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20278', 'locality' => 'Aguascalientes', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20280', 'locality' => 'Aguascalientes', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20283', 'locality' => 'Aguascalientes', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20284', 'locality' => 'Aguascalientes', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20285', 'locality' => 'Aguascalientes', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20286', 'locality' => 'Aguascalientes', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20287', 'locality' => 'Aguascalientes', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20288', 'locality' => 'Aguascalientes', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20289', 'locality' => 'Aguascalientes', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20290', 'locality' => 'Aguascalientes', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20291', 'locality' => 'Aguascalientes', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20296', 'locality' => 'Aguascalientes', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20297', 'locality' => 'Aguascalientes', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20298', 'locality' => 'Aguascalientes', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20299', 'locality' => 'Aguascalientes', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20310', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20313', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20314', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20316', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20319', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20320', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20323', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20324', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20326', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20328', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20329', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20340', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20341', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20342', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20343', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20344', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20345', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20346', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20347', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20348', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20349', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20363', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20364', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20366', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20367', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20369', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20370', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20371', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20372', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20373', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20374', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20375', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20376', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20377', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20378', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20384', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20385', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20386', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20388', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20389', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20392', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20393', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20394', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20395', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20396', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20700', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20704', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20705', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20706', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20708', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20709', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20710', 'locality' => 'Asientos', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20712', 'locality' => 'Asientos', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20713', 'locality' => 'Asientos', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20714', 'locality' => 'Asientos', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20715', 'locality' => 'Asientos', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20717', 'locality' => 'Asientos', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20720', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20721', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20722', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20723', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20724', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20727', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20729', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20730', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20734', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20736', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20737', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20739', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20740', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20741', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20742', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20744', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20746', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20748', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20749', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20750', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20768', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20770', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20773', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20780', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20782', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20785', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20790', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20795', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20796', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20799', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20800', 'locality' => 'Calvillo', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20802', 'locality' => 'Calvillo', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20803', 'locality' => 'Calvillo', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20804', 'locality' => 'Calvillo', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20805', 'locality' => 'Calvillo', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20810', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20816', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20820', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20823', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20830', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20832', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20834', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20835', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20836', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20840', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20842', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20844', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20850', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20852', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20854', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20855', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20856', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20860', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20862', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20864', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20870', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20872', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20874', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20880', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20882', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20460', 'locality' => 'Cosío', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20462', 'locality' => 'Cosío', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20466', 'locality' => 'Cosío', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20467', 'locality' => 'Cosío', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20468', 'locality' => 'Cosío', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20469', 'locality' => 'Cosío', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20470', 'locality' => '', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20472', 'locality' => '', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20476', 'locality' => '', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20478', 'locality' => '', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20330', 'locality' => '', 'municipality_id' => Municipality::where('key', 10)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20333', 'locality' => '', 'municipality_id' => Municipality::where('key', 10)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20334', 'locality' => '', 'municipality_id' => Municipality::where('key', 10)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20335', 'locality' => '', 'municipality_id' => Municipality::where('key', 10)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20336', 'locality' => '', 'municipality_id' => Municipality::where('key', 10)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20337', 'locality' => '', 'municipality_id' => Municipality::where('key', 10)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20338', 'locality' => '', 'municipality_id' => Municipality::where('key', 10)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20339', 'locality' => '', 'municipality_id' => Municipality::where('key', 10)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20900', 'locality' => '', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20901', 'locality' => '', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20903', 'locality' => '', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20904', 'locality' => '', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20905', 'locality' => '', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20907', 'locality' => '', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20908', 'locality' => '', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20909', 'locality' => '', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20910', 'locality' => '', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20913', 'locality' => '', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20914', 'locality' => '', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20915', 'locality' => '', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20916', 'locality' => '', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20917', 'locality' => '', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20920', 'locality' => 'Jesús María', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20922', 'locality' => 'Jesús María', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20923', 'locality' => 'Jesús María', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20924', 'locality' => 'Jesús María', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20925', 'locality' => 'Jesús María', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20926', 'locality' => 'Jesús María', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20927', 'locality' => 'Jesús María', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20928', 'locality' => 'Jesús María', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20933', 'locality' => '', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20934', 'locality' => '', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20943', 'locality' => '', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20947', 'locality' => '', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20953', 'locality' => '', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20954', 'locality' => '', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20955', 'locality' => '', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20956', 'locality' => '', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20957', 'locality' => '', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20970', 'locality' => '', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20974', 'locality' => '', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20983', 'locality' => '', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20984', 'locality' => '', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20990', 'locality' => '', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20994', 'locality' => '', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20995', 'locality' => '', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20996', 'locality' => '', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20997', 'locality' => '', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20663', 'locality' => '', 'municipality_id' => Municipality::where('key', 6)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20665', 'locality' => '', 'municipality_id' => Municipality::where('key', 6)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20666', 'locality' => '', 'municipality_id' => Municipality::where('key', 6)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20667', 'locality' => '', 'municipality_id' => Municipality::where('key', 6)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20668', 'locality' => '', 'municipality_id' => Municipality::where('key', 6)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20670', 'locality' => 'Pabellón de Arteaga', 'municipality_id' => Municipality::where('key', 6)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20673', 'locality' => 'Pabellón de Arteaga', 'municipality_id' => Municipality::where('key', 6)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20674', 'locality' => 'Pabellón de Arteaga', 'municipality_id' => Municipality::where('key', 6)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20675', 'locality' => 'Pabellón de Arteaga', 'municipality_id' => Municipality::where('key', 6)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20676', 'locality' => 'Pabellón de Arteaga', 'municipality_id' => Municipality::where('key', 6)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20677', 'locality' => 'Pabellón de Arteaga', 'municipality_id' => Municipality::where('key', 6)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20678', 'locality' => 'Pabellón de Arteaga', 'municipality_id' => Municipality::where('key', 6)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20680', 'locality' => '', 'municipality_id' => Municipality::where('key', 6)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20683', 'locality' => '', 'municipality_id' => Municipality::where('key', 6)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20684', 'locality' => '', 'municipality_id' => Municipality::where('key', 6)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20686', 'locality' => '', 'municipality_id' => Municipality::where('key', 6)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20687', 'locality' => '', 'municipality_id' => Municipality::where('key', 6)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20400', 'locality' => 'Rincón de Romos', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20403', 'locality' => 'Rincón de Romos', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20404', 'locality' => 'Rincón de Romos', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20405', 'locality' => 'Rincón de Romos', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20406', 'locality' => 'Rincón de Romos', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20410', 'locality' => 'Rincón de Romos', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20414', 'locality' => 'Rincón de Romos', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20415', 'locality' => 'Rincón de Romos', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20416', 'locality' => 'Rincón de Romos', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20417', 'locality' => 'Rincón de Romos', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20420', 'locality' => '', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20423', 'locality' => '', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20424', 'locality' => '', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20425', 'locality' => '', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20426', 'locality' => '', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20427', 'locality' => '', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20430', 'locality' => '', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20434', 'locality' => '', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20435', 'locality' => '', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20436', 'locality' => '', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20437', 'locality' => '', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20440', 'locality' => '', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20444', 'locality' => '', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20450', 'locality' => '', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20454', 'locality' => '', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20300', 'locality' => 'San Francisco de los Romo', 'municipality_id' => Municipality::where('key', 11)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20303', 'locality' => 'San Francisco de los Romo', 'municipality_id' => Municipality::where('key', 11)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20304', 'locality' => 'San Francisco de los Romo', 'municipality_id' => Municipality::where('key', 11)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20305', 'locality' => 'San Francisco de los Romo', 'municipality_id' => Municipality::where('key', 11)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20306', 'locality' => 'San Francisco de los Romo', 'municipality_id' => Municipality::where('key', 11)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20350', 'locality' => '', 'municipality_id' => Municipality::where('key', 11)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20355', 'locality' => '', 'municipality_id' => Municipality::where('key', 11)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20356', 'locality' => '', 'municipality_id' => Municipality::where('key', 11)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20357', 'locality' => '', 'municipality_id' => Municipality::where('key', 11)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20358', 'locality' => '', 'municipality_id' => Municipality::where('key', 11)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20500', 'locality' => '', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20502', 'locality' => '', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20503', 'locality' => '', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20504', 'locality' => '', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20508', 'locality' => '', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20510', 'locality' => '', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20516', 'locality' => '', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20520', 'locality' => '', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20534', 'locality' => '', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20538', 'locality' => '', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20540', 'locality' => '', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20545', 'locality' => '', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20563', 'locality' => '', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20564', 'locality' => '', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20567', 'locality' => '', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20570', 'locality' => '', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20574', 'locality' => '', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20575', 'locality' => '', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20576', 'locality' => '', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20600', 'locality' => 'Tepezalá', 'municipality_id' => Municipality::where('key', 9)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20602', 'locality' => 'Tepezalá', 'municipality_id' => Municipality::where('key', 9)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20603', 'locality' => 'Tepezalá', 'municipality_id' => Municipality::where('key', 9)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20604', 'locality' => 'Tepezalá', 'municipality_id' => Municipality::where('key', 9)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20607', 'locality' => 'Tepezalá', 'municipality_id' => Municipality::where('key', 9)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20610', 'locality' => '', 'municipality_id' => Municipality::where('key', 9)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20614', 'locality' => '', 'municipality_id' => Municipality::where('key', 9)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20615', 'locality' => '', 'municipality_id' => Municipality::where('key', 9)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20616', 'locality' => '', 'municipality_id' => Municipality::where('key', 9)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20620', 'locality' => '', 'municipality_id' => Municipality::where('key', 9)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20622', 'locality' => '', 'municipality_id' => Municipality::where('key', 9)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20634', 'locality' => '', 'municipality_id' => Municipality::where('key', 9)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20635', 'locality' => '', 'municipality_id' => Municipality::where('key', 9)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20637', 'locality' => '', 'municipality_id' => Municipality::where('key', 9)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20650', 'locality' => '', 'municipality_id' => Municipality::where('key', 9)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20656', 'locality' => '', 'municipality_id' => Municipality::where('key', 9)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20657', 'locality' => '', 'municipality_id' => Municipality::where('key', 9)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20658', 'locality' => '', 'municipality_id' => Municipality::where('key', 9)->where('state_id', 1)->first()->id , 'state_id' => 1],
            [ 'zip_code' => '20659', 'locality' => '', 'municipality_id' => Municipality::where('key', 9)->where('state_id', 1)->first()->id , 'state_id' => 1],
        ];

        ZipCode::insert($zipCodes);
        unset($zipCodes);
    }
}
