<?php

namespace Database\Seeders;

use App\Models\ZipCode;
use App\Models\Municipality;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class BajaCaliforniaSurZipCodesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $zipCodes = [
            [ 'zip_code' => '23000', 'locality' => 'La Paz', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23007', 'locality' => 'La Paz', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23009', 'locality' => 'La Paz', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23010', 'locality' => 'La Paz', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23017', 'locality' => 'La Paz', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23018', 'locality' => 'La Paz', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23019', 'locality' => 'La Paz', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23020', 'locality' => 'La Paz', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23026', 'locality' => 'La Paz', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23029', 'locality' => 'La Paz', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23030', 'locality' => 'La Paz', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23034', 'locality' => 'La Paz', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23037', 'locality' => 'La Paz', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23038', 'locality' => 'La Paz', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23039', 'locality' => 'La Paz', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23040', 'locality' => 'La Paz', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23050', 'locality' => 'La Paz', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23052', 'locality' => 'La Paz', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23054', 'locality' => 'La Paz', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23055', 'locality' => 'La Paz', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23056', 'locality' => 'La Paz', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23060', 'locality' => 'La Paz', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23070', 'locality' => 'La Paz', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23075', 'locality' => 'La Paz', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23076', 'locality' => 'La Paz', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23077', 'locality' => 'La Paz', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23078', 'locality' => 'La Paz', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23079', 'locality' => 'La Paz', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23080', 'locality' => 'La Paz', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23083', 'locality' => 'La Paz', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23084', 'locality' => 'La Paz', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23085', 'locality' => 'La Paz', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23086', 'locality' => 'La Paz', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23088', 'locality' => 'La Paz', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23089', 'locality' => 'La Paz', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23090', 'locality' => 'La Paz', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23094', 'locality' => 'La Paz', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23095', 'locality' => 'La Paz', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23096', 'locality' => 'La Paz', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23097', 'locality' => 'La Paz', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23098', 'locality' => 'La Paz', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23099', 'locality' => 'La Paz', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23100', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23106', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23130', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23133', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23134', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23140', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23143', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23150', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23154', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23170', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23174', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23200', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23203', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23205', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23206', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23208', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23209', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23210', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23213', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23215', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23216', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23217', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23230', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23232', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23234', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23236', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23240', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23243', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23244', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23247', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23248', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23249', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23250', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23252', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23257', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23258', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23280', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23283', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23289', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23300', 'locality' => 'Todos Santos', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23302', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23303', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23304', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23308', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23311', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23312', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23317', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23320', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23322', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23328', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23329', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23330', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23333', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23334', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23350', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23354', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23360', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23361', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23362', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23363', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23364', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23365', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23366', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23390', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23395', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23400', 'locality' => 'San José del Cabo', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23403', 'locality' => 'San José del Cabo', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23405', 'locality' => 'San José del Cabo', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23406', 'locality' => 'San José del Cabo', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23407', 'locality' => 'San José del Cabo', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23420', 'locality' => 'San José del Cabo', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23425', 'locality' => 'San José del Cabo', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23426', 'locality' => 'San José del Cabo', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23427', 'locality' => 'San José del Cabo', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23428', 'locality' => 'San José del Cabo', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23429', 'locality' => 'San José del Cabo', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23434', 'locality' => 'San José del Cabo', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23435', 'locality' => 'San José del Cabo', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23436', 'locality' => 'San José del Cabo', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23437', 'locality' => 'San José del Cabo', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23440', 'locality' => 'San José del Cabo', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23443', 'locality' => 'San José del Cabo', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23444', 'locality' => 'San José del Cabo', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23445', 'locality' => 'San José del Cabo', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23450', 'locality' => 'Cabo San Lucas', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23453', 'locality' => 'Cabo San Lucas', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23454', 'locality' => 'Cabo San Lucas', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23455', 'locality' => 'Cabo San Lucas', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23456', 'locality' => 'Cabo San Lucas', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23460', 'locality' => 'Cabo San Lucas', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23462', 'locality' => 'Cabo San Lucas', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23463', 'locality' => 'Cabo San Lucas', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23467', 'locality' => 'Cabo San Lucas', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23468', 'locality' => 'Cabo San Lucas', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23469', 'locality' => 'Cabo San Lucas', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23470', 'locality' => 'Cabo San Lucas', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23472', 'locality' => 'Cabo San Lucas', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23473', 'locality' => 'Cabo San Lucas', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23474', 'locality' => 'Cabo San Lucas', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23475', 'locality' => 'Cabo San Lucas', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23477', 'locality' => 'Cabo San Lucas', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23478', 'locality' => 'Cabo San Lucas', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23500', 'locality' => '', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23501', 'locality' => '', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23503', 'locality' => '', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23510', 'locality' => '', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23520', 'locality' => '', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23522', 'locality' => '', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23523', 'locality' => '', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23530', 'locality' => '', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23533', 'locality' => '', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23535', 'locality' => '', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23560', 'locality' => '', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23563', 'locality' => '', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23567', 'locality' => '', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23570', 'locality' => '', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23574', 'locality' => '', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23575', 'locality' => '', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23580', 'locality' => '', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23581', 'locality' => '', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23586', 'locality' => '', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23590', 'locality' => '', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23593', 'locality' => '', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23597', 'locality' => '', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23600', 'locality' => 'Ciudad Constitución', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23610', 'locality' => 'Ciudad Constitución', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23620', 'locality' => 'Ciudad Constitución', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23630', 'locality' => 'Ciudad Constitución', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23640', 'locality' => 'Ciudad Constitución', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23641', 'locality' => 'Ciudad Constitución', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23650', 'locality' => 'Ciudad Constitución', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23653', 'locality' => 'Ciudad Constitución', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23658', 'locality' => 'Ciudad Constitución', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23660', 'locality' => 'Ciudad Constitución', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23670', 'locality' => 'Ciudad Constitución', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23676', 'locality' => 'Ciudad Constitución', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23677', 'locality' => 'Ciudad Constitución', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23678', 'locality' => 'Ciudad Constitución', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23680', 'locality' => 'Ciudad Constitución', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23683', 'locality' => 'Ciudad Constitución', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23690', 'locality' => 'Ciudad Constitución', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23695', 'locality' => 'Ciudad Constitución', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23696', 'locality' => 'Ciudad Constitución', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23697', 'locality' => 'Ciudad Constitución', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23700', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23708', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23710', 'locality' => 'Puerto Adolfo López Mateos', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23715', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23720', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23721', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23723', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23730', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23734', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23736', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23737', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23739', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23740', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23743', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23748', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23749', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23750', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23760', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23765', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23766', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23767', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23770', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23771', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23774', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23775', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23780', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23789', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23790', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23800', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23805', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23810', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23812', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23813', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23818', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23820', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23824', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23830', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23834', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23837', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23838', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23840', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23844', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23845', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23860', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23870', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23873', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23880', 'locality' => 'Loreto', 'municipality_id' => Municipality::where('key', 9)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23883', 'locality' => '', 'municipality_id' => Municipality::where('key', 9)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23884', 'locality' => '', 'municipality_id' => Municipality::where('key', 9)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23885', 'locality' => '', 'municipality_id' => Municipality::where('key', 9)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23886', 'locality' => '', 'municipality_id' => Municipality::where('key', 9)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23887', 'locality' => '', 'municipality_id' => Municipality::where('key', 9)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23888', 'locality' => '', 'municipality_id' => Municipality::where('key', 9)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23889', 'locality' => '', 'municipality_id' => Municipality::where('key', 9)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23890', 'locality' => '', 'municipality_id' => Municipality::where('key', 9)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23893', 'locality' => '', 'municipality_id' => Municipality::where('key', 9)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23894', 'locality' => '', 'municipality_id' => Municipality::where('key', 9)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23895', 'locality' => '', 'municipality_id' => Municipality::where('key', 9)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23896', 'locality' => '', 'municipality_id' => Municipality::where('key', 9)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23897', 'locality' => '', 'municipality_id' => Municipality::where('key', 9)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23898', 'locality' => '', 'municipality_id' => Municipality::where('key', 9)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23900', 'locality' => 'Heroica Mulegé', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23902', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23903', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23904', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23910', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23911', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23912', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23913', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23914', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23915', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23916', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23917', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23920', 'locality' => 'Santa Rosalía', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23921', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23922', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23923', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23924', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23930', 'locality' => 'San Ignacio', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23934', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23935', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23936', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23938', 'locality' => 'Villa Alberto Andrés Alvarado Arámburo', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23940', 'locality' => 'Guerrero Negro', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23944', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23948', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23949', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23950', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23951', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23952', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23959', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23960', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23969', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23970', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23971', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23972', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23973', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23980', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23983', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23988', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23990', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 3)->first()->id , 'state_id' => 3],
            [ 'zip_code' => '23997', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 3)->first()->id , 'state_id' => 3],
        ];

        ZipCode::insert($zipCodes);
        unset($zipCodes);
    }
}
