<?php

namespace Database\Seeders;

use App\Models\ZipCode;
use App\Models\Municipality;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class CampecheZipCodesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $zipCodes = [
            [ 'zip_code' => '24000', 'locality' => 'San Francisco de Campeche', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24010', 'locality' => 'San Francisco de Campeche', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24014', 'locality' => 'San Francisco de Campeche', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24020', 'locality' => 'San Francisco de Campeche', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24022', 'locality' => 'San Francisco de Campeche', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24023', 'locality' => 'San Francisco de Campeche', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24024', 'locality' => 'San Francisco de Campeche', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24025', 'locality' => 'San Francisco de Campeche', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24026', 'locality' => 'San Francisco de Campeche', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24027', 'locality' => 'San Francisco de Campeche', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24028', 'locality' => 'San Francisco de Campeche', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24029', 'locality' => 'San Francisco de Campeche', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24030', 'locality' => 'San Francisco de Campeche', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24035', 'locality' => 'San Francisco de Campeche', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24036', 'locality' => 'San Francisco de Campeche', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24037', 'locality' => 'San Francisco de Campeche', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24038', 'locality' => 'San Francisco de Campeche', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24039', 'locality' => 'San Francisco de Campeche', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24040', 'locality' => 'San Francisco de Campeche', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24044', 'locality' => 'San Francisco de Campeche', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24049', 'locality' => 'San Francisco de Campeche', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24050', 'locality' => 'San Francisco de Campeche', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24058', 'locality' => 'San Francisco de Campeche', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24060', 'locality' => 'San Francisco de Campeche', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24069', 'locality' => 'San Francisco de Campeche', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24070', 'locality' => 'San Francisco de Campeche', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24073', 'locality' => 'San Francisco de Campeche', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24075', 'locality' => 'San Francisco de Campeche', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24079', 'locality' => 'San Francisco de Campeche', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24080', 'locality' => 'San Francisco de Campeche', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24083', 'locality' => 'San Francisco de Campeche', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24084', 'locality' => 'San Francisco de Campeche', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24085', 'locality' => 'San Francisco de Campeche', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24086', 'locality' => 'San Francisco de Campeche', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24087', 'locality' => 'San Francisco de Campeche', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24088', 'locality' => 'San Francisco de Campeche', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24089', 'locality' => 'San Francisco de Campeche', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24090', 'locality' => 'San Francisco de Campeche', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24093', 'locality' => 'San Francisco de Campeche', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24094', 'locality' => 'San Francisco de Campeche', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24095', 'locality' => 'San Francisco de Campeche', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24096', 'locality' => 'San Francisco de Campeche', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24097', 'locality' => 'San Francisco de Campeche', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24098', 'locality' => 'San Francisco de Campeche', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24099', 'locality' => 'San Francisco de Campeche', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24100', 'locality' => 'Ciudad del Carmen', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24108', 'locality' => 'Ciudad del Carmen', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24110', 'locality' => 'Ciudad del Carmen', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24114', 'locality' => 'Ciudad del Carmen', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24115', 'locality' => 'Ciudad del Carmen', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24116', 'locality' => 'Ciudad del Carmen', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24117', 'locality' => 'Ciudad del Carmen', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24118', 'locality' => 'Ciudad del Carmen', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24119', 'locality' => 'Ciudad del Carmen', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24120', 'locality' => 'Ciudad del Carmen', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24129', 'locality' => 'Ciudad del Carmen', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24130', 'locality' => 'Ciudad del Carmen', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24139', 'locality' => 'Ciudad del Carmen', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24140', 'locality' => 'Ciudad del Carmen', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24150', 'locality' => 'Ciudad del Carmen', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24153', 'locality' => 'Ciudad del Carmen', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24154', 'locality' => 'Ciudad del Carmen', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24155', 'locality' => 'Ciudad del Carmen', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24156', 'locality' => 'Ciudad del Carmen', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24157', 'locality' => 'Ciudad del Carmen', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24158', 'locality' => 'Ciudad del Carmen', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24160', 'locality' => 'Ciudad del Carmen', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24166', 'locality' => 'Ciudad del Carmen', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24167', 'locality' => 'Ciudad del Carmen', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24169', 'locality' => 'Ciudad del Carmen', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24170', 'locality' => 'Ciudad del Carmen', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24178', 'locality' => 'Ciudad del Carmen', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24179', 'locality' => 'Ciudad del Carmen', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24180', 'locality' => 'Ciudad del Carmen', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24185', 'locality' => 'Ciudad del Carmen', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24186', 'locality' => 'Ciudad del Carmen', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24187', 'locality' => 'Ciudad del Carmen', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24188', 'locality' => 'Ciudad del Carmen', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24189', 'locality' => 'Ciudad del Carmen', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24190', 'locality' => 'Ciudad del Carmen', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24195', 'locality' => 'Ciudad del Carmen', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24197', 'locality' => 'Ciudad del Carmen', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24198', 'locality' => 'Ciudad del Carmen', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24199', 'locality' => 'Ciudad del Carmen', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24200', 'locality' => '', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24203', 'locality' => '', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24204', 'locality' => '', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24205', 'locality' => '', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24206', 'locality' => '', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24207', 'locality' => '', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24208', 'locality' => '', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24300', 'locality' => 'Sabancuy', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24310', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24313', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24314', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24315', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24316', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24317', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24320', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24322', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24323', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24324', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24325', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24326', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24327', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24330', 'locality' => 'Candelaria', 'municipality_id' => Municipality::where('key', 11)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24333', 'locality' => '', 'municipality_id' => Municipality::where('key', 11)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24334', 'locality' => '', 'municipality_id' => Municipality::where('key', 11)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24335', 'locality' => '', 'municipality_id' => Municipality::where('key', 11)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24336', 'locality' => '', 'municipality_id' => Municipality::where('key', 11)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24337', 'locality' => '', 'municipality_id' => Municipality::where('key', 11)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24338', 'locality' => '', 'municipality_id' => Municipality::where('key', 11)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24342', 'locality' => '', 'municipality_id' => Municipality::where('key', 11)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24343', 'locality' => '', 'municipality_id' => Municipality::where('key', 11)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24344', 'locality' => '', 'municipality_id' => Municipality::where('key', 11)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24345', 'locality' => '', 'municipality_id' => Municipality::where('key', 11)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24346', 'locality' => '', 'municipality_id' => Municipality::where('key', 11)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24347', 'locality' => '', 'municipality_id' => Municipality::where('key', 11)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24348', 'locality' => '', 'municipality_id' => Municipality::where('key', 11)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24350', 'locality' => 'Escárcega', 'municipality_id' => Municipality::where('key', 9)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24353', 'locality' => '', 'municipality_id' => Municipality::where('key', 9)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24354', 'locality' => '', 'municipality_id' => Municipality::where('key', 9)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24355', 'locality' => '', 'municipality_id' => Municipality::where('key', 9)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24356', 'locality' => '', 'municipality_id' => Municipality::where('key', 9)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24357', 'locality' => '', 'municipality_id' => Municipality::where('key', 9)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24358', 'locality' => '', 'municipality_id' => Municipality::where('key', 9)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24364', 'locality' => '', 'municipality_id' => Municipality::where('key', 9)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24365', 'locality' => '', 'municipality_id' => Municipality::where('key', 9)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24366', 'locality' => '', 'municipality_id' => Municipality::where('key', 9)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24367', 'locality' => '', 'municipality_id' => Municipality::where('key', 9)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24368', 'locality' => '', 'municipality_id' => Municipality::where('key', 9)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24369', 'locality' => '', 'municipality_id' => Municipality::where('key', 9)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24370', 'locality' => '', 'municipality_id' => Municipality::where('key', 9)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24372', 'locality' => '', 'municipality_id' => Municipality::where('key', 9)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24373', 'locality' => '', 'municipality_id' => Municipality::where('key', 9)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24374', 'locality' => '', 'municipality_id' => Municipality::where('key', 9)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24375', 'locality' => '', 'municipality_id' => Municipality::where('key', 9)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24376', 'locality' => '', 'municipality_id' => Municipality::where('key', 9)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24377', 'locality' => '', 'municipality_id' => Municipality::where('key', 9)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24400', 'locality' => 'Champotón', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24402', 'locality' => '', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24404', 'locality' => '', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24410', 'locality' => '', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24411', 'locality' => '', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24413', 'locality' => '', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24414', 'locality' => '', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24415', 'locality' => '', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24416', 'locality' => '', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24418', 'locality' => '', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24419', 'locality' => '', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24420', 'locality' => '', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24421', 'locality' => '', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24423', 'locality' => '', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24424', 'locality' => '', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24440', 'locality' => '', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24441', 'locality' => '', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24443', 'locality' => '', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24450', 'locality' => '', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24451', 'locality' => '', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24459', 'locality' => '', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24460', 'locality' => '', 'municipality_id' => Municipality::where('key', 12)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24462', 'locality' => '', 'municipality_id' => Municipality::where('key', 12)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24464', 'locality' => '', 'municipality_id' => Municipality::where('key', 12)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24500', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24505', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24517', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24520', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24522', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24523', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24532', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24536', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24537', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24540', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24550', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24552', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24553', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24557', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24560', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24561', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24562', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24564', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24570', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24572', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24573', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24574', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24575', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24600', 'locality' => 'Hopelchén', 'municipality_id' => Municipality::where('key', 6)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24604', 'locality' => '', 'municipality_id' => Municipality::where('key', 6)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24605', 'locality' => '', 'municipality_id' => Municipality::where('key', 6)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24606', 'locality' => '', 'municipality_id' => Municipality::where('key', 6)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24607', 'locality' => '', 'municipality_id' => Municipality::where('key', 6)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24609', 'locality' => '', 'municipality_id' => Municipality::where('key', 6)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24610', 'locality' => '', 'municipality_id' => Municipality::where('key', 6)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24611', 'locality' => '', 'municipality_id' => Municipality::where('key', 6)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24612', 'locality' => '', 'municipality_id' => Municipality::where('key', 6)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24613', 'locality' => '', 'municipality_id' => Municipality::where('key', 6)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24615', 'locality' => '', 'municipality_id' => Municipality::where('key', 6)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24620', 'locality' => '', 'municipality_id' => Municipality::where('key', 6)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24622', 'locality' => '', 'municipality_id' => Municipality::where('key', 6)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24623', 'locality' => '', 'municipality_id' => Municipality::where('key', 6)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24624', 'locality' => '', 'municipality_id' => Municipality::where('key', 6)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24640', 'locality' => '', 'municipality_id' => Municipality::where('key', 10)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24643', 'locality' => '', 'municipality_id' => Municipality::where('key', 10)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24644', 'locality' => '', 'municipality_id' => Municipality::where('key', 10)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24645', 'locality' => '', 'municipality_id' => Municipality::where('key', 10)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24646', 'locality' => '', 'municipality_id' => Municipality::where('key', 10)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24647', 'locality' => '', 'municipality_id' => Municipality::where('key', 10)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24648', 'locality' => '', 'municipality_id' => Municipality::where('key', 10)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24653', 'locality' => '', 'municipality_id' => Municipality::where('key', 10)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24654', 'locality' => '', 'municipality_id' => Municipality::where('key', 10)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24656', 'locality' => '', 'municipality_id' => Municipality::where('key', 10)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24658', 'locality' => '', 'municipality_id' => Municipality::where('key', 10)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24660', 'locality' => '', 'municipality_id' => Municipality::where('key', 6)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24663', 'locality' => '', 'municipality_id' => Municipality::where('key', 6)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24667', 'locality' => '', 'municipality_id' => Municipality::where('key', 6)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24668', 'locality' => '', 'municipality_id' => Municipality::where('key', 6)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24670', 'locality' => '', 'municipality_id' => Municipality::where('key', 6)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24700', 'locality' => 'Tenabo', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24703', 'locality' => 'Tenabo', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24704', 'locality' => 'Tenabo', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24705', 'locality' => 'Tenabo', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24706', 'locality' => 'Tenabo', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24707', 'locality' => 'Tenabo', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24720', 'locality' => '', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24723', 'locality' => '', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24730', 'locality' => '', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24732', 'locality' => '', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24733', 'locality' => '', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24734', 'locality' => '', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24740', 'locality' => '', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24746', 'locality' => '', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24800', 'locality' => 'Hecelchakán', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24810', 'locality' => 'Pomuch', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24813', 'locality' => '', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24820', 'locality' => '', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24826', 'locality' => '', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24828', 'locality' => '', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24830', 'locality' => '', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24831', 'locality' => '', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24836', 'locality' => '', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24837', 'locality' => '', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24839', 'locality' => '', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24860', 'locality' => '', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24863', 'locality' => '', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24900', 'locality' => 'Calkini', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24902', 'locality' => 'Calkini', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24903', 'locality' => 'Calkini', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24904', 'locality' => 'Calkini', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24905', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24910', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24913', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24914', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24915', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24916', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24917', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24919', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24920', 'locality' => '', 'municipality_id' => Municipality::where('key', 13)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24925', 'locality' => '', 'municipality_id' => Municipality::where('key', 13)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24929', 'locality' => '', 'municipality_id' => Municipality::where('key', 13)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24930', 'locality' => 'Bécal', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24933', 'locality' => 'Bécal', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24934', 'locality' => 'Bécal', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24935', 'locality' => 'Bécal', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24936', 'locality' => 'Bécal', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 4)->first()->id , 'state_id' => 4],
            [ 'zip_code' => '24940', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 4)->first()->id , 'state_id' => 4],
        ];

        ZipCode::insert($zipCodes);
        unset($zipCodes);
    }
}
