<?php

namespace Database\Seeders;

use App\Models\Municipality;
use App\Models\ZipCode;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class ColimaZipCodesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $zipCodes = [
            [ 'zip_code' => '28000', 'locality' => 'Colima', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28010', 'locality' => 'Colima', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28014', 'locality' => 'Colima', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28016', 'locality' => 'Colima', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28017', 'locality' => 'Colima', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28018', 'locality' => 'Colima', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28019', 'locality' => 'Colima', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28020', 'locality' => 'Colima', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28023', 'locality' => 'Colima', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28025', 'locality' => 'Colima', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28030', 'locality' => 'Colima', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28035', 'locality' => 'Colima', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28037', 'locality' => 'Colima', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28040', 'locality' => 'Colima', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28043', 'locality' => 'Colima', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28044', 'locality' => 'Colima', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28045', 'locality' => 'Colima', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28046', 'locality' => 'Colima', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28047', 'locality' => 'Colima', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28048', 'locality' => 'Colima', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28050', 'locality' => 'Colima', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28060', 'locality' => 'Colima', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28063', 'locality' => 'Colima', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28067', 'locality' => 'Colima', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28070', 'locality' => 'Colima', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28075', 'locality' => 'Colima', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28077', 'locality' => 'Colima', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28078', 'locality' => 'Colima', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28079', 'locality' => 'Colima', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28080', 'locality' => 'Colima', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28085', 'locality' => 'Colima', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28089', 'locality' => 'Colima', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28090', 'locality' => 'Colima', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28100', 'locality' => 'Tecomán', 'municipality_id' => Municipality::where('key', 9)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28110', 'locality' => 'Tecomán', 'municipality_id' => Municipality::where('key', 9)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28113', 'locality' => 'Tecomán', 'municipality_id' => Municipality::where('key', 9)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28114', 'locality' => 'Tecomán', 'municipality_id' => Municipality::where('key', 9)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28120', 'locality' => 'Tecomán', 'municipality_id' => Municipality::where('key', 9)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28123', 'locality' => 'Tecomán', 'municipality_id' => Municipality::where('key', 9)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28130', 'locality' => 'Tecomán', 'municipality_id' => Municipality::where('key', 9)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28133', 'locality' => 'Tecomán', 'municipality_id' => Municipality::where('key', 9)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28134', 'locality' => 'Tecomán', 'municipality_id' => Municipality::where('key', 9)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28140', 'locality' => 'Tecomán', 'municipality_id' => Municipality::where('key', 9)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28143', 'locality' => 'Tecomán', 'municipality_id' => Municipality::where('key', 9)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28150', 'locality' => 'Tecomán', 'municipality_id' => Municipality::where('key', 9)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28159', 'locality' => 'Tecomán', 'municipality_id' => Municipality::where('key', 9)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28160', 'locality' => 'Tecomán', 'municipality_id' => Municipality::where('key', 9)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28170', 'locality' => 'Tecomán', 'municipality_id' => Municipality::where('key', 9)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28180', 'locality' => 'Tecomán', 'municipality_id' => Municipality::where('key', 9)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28184', 'locality' => 'Tecomán', 'municipality_id' => Municipality::where('key', 9)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28189', 'locality' => 'Tecomán', 'municipality_id' => Municipality::where('key', 9)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28190', 'locality' => 'Tecomán', 'municipality_id' => Municipality::where('key', 9)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28200', 'locality' => 'Manzanillo', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28209', 'locality' => 'Manzanillo', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28218', 'locality' => 'Manzanillo', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28219', 'locality' => 'Manzanillo', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28230', 'locality' => 'Manzanillo', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28236', 'locality' => 'Manzanillo', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28237', 'locality' => 'Manzanillo', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28238', 'locality' => 'Manzanillo', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28239', 'locality' => 'Manzanillo', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28240', 'locality' => 'Manzanillo', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28250', 'locality' => 'Manzanillo', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28259', 'locality' => 'Manzanillo', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28260', 'locality' => 'Manzanillo', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28269', 'locality' => 'Manzanillo', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28270', 'locality' => 'Manzanillo', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28278', 'locality' => 'Manzanillo', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28279', 'locality' => 'Manzanillo', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28300', 'locality' => 'Ciudad de Armería', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28304', 'locality' => 'Ciudad de Armería', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28305', 'locality' => 'Ciudad de Armería', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28306', 'locality' => 'Ciudad de Armería', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28307', 'locality' => 'Ciudad de Armería', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28310', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28313', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28315', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28317', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28320', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28330', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28340', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28350', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28400', 'locality' => '', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28402', 'locality' => '', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28403', 'locality' => '', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28405', 'locality' => '', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28410', 'locality' => '', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28413', 'locality' => '', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28414', 'locality' => '', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28420', 'locality' => '', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28424', 'locality' => '', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28450', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28452', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28454', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28455', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28456', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28459', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28460', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28461', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28464', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28466', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28500', 'locality' => '', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28504', 'locality' => '', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28506', 'locality' => '', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28507', 'locality' => '', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28510', 'locality' => '', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28513', 'locality' => '', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28515', 'locality' => '', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28516', 'locality' => '', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28520', 'locality' => '', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28521', 'locality' => '', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28523', 'locality' => '', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28530', 'locality' => '', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28531', 'locality' => '', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28550', 'locality' => '', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28553', 'locality' => '', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28555', 'locality' => '', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28557', 'locality' => '', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28590', 'locality' => '', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28597', 'locality' => '', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28599', 'locality' => '', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28600', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28610', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28613', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28620', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28626', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28627', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28628', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28629', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28630', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28633', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28634', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28635', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28640', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28645', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28646', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28647', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28655', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28656', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28700', 'locality' => '', 'municipality_id' => Municipality::where('key', 6)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28703', 'locality' => '', 'municipality_id' => Municipality::where('key', 6)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28704', 'locality' => '', 'municipality_id' => Municipality::where('key', 6)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28705', 'locality' => '', 'municipality_id' => Municipality::where('key', 6)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28720', 'locality' => '', 'municipality_id' => Municipality::where('key', 6)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28724', 'locality' => '', 'municipality_id' => Municipality::where('key', 6)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28730', 'locality' => '', 'municipality_id' => Municipality::where('key', 6)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28733', 'locality' => '', 'municipality_id' => Municipality::where('key', 6)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28734', 'locality' => '', 'municipality_id' => Municipality::where('key', 6)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28735', 'locality' => '', 'municipality_id' => Municipality::where('key', 6)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28736', 'locality' => '', 'municipality_id' => Municipality::where('key', 6)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28750', 'locality' => '', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28760', 'locality' => '', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28764', 'locality' => '', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28765', 'locality' => '', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28766', 'locality' => '', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28767', 'locality' => '', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28770', 'locality' => '', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28772', 'locality' => '', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28773', 'locality' => '', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28774', 'locality' => '', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28780', 'locality' => '', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28784', 'locality' => '', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28800', 'locality' => '', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28807', 'locality' => '', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28808', 'locality' => '', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28809', 'locality' => '', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28810', 'locality' => '', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28812', 'locality' => '', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28813', 'locality' => '', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28814', 'locality' => '', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28815', 'locality' => '', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28820', 'locality' => '', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28826', 'locality' => '', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28830', 'locality' => '', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28833', 'locality' => '', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28834', 'locality' => '', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28836', 'locality' => '', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28838', 'locality' => '', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28840', 'locality' => '', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28850', 'locality' => '', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28855', 'locality' => '', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28860', 'locality' => 'Manzanillo', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28863', 'locality' => 'Manzanillo', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28864', 'locality' => 'Manzanillo', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28865', 'locality' => 'Manzanillo', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28867', 'locality' => 'Manzanillo', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28868', 'locality' => 'Manzanillo', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28869', 'locality' => 'Manzanillo', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28870', 'locality' => '', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28872', 'locality' => '', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28880', 'locality' => '', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28885', 'locality' => '', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28886', 'locality' => '', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28900', 'locality' => '', 'municipality_id' => Municipality::where('key', 9)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28910', 'locality' => '', 'municipality_id' => Municipality::where('key', 9)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28915', 'locality' => '', 'municipality_id' => Municipality::where('key', 9)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28920', 'locality' => '', 'municipality_id' => Municipality::where('key', 9)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28923', 'locality' => '', 'municipality_id' => Municipality::where('key', 9)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28929', 'locality' => '', 'municipality_id' => Municipality::where('key', 9)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28930', 'locality' => '', 'municipality_id' => Municipality::where('key', 9)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28934', 'locality' => '', 'municipality_id' => Municipality::where('key', 9)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28935', 'locality' => '', 'municipality_id' => Municipality::where('key', 9)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28936', 'locality' => '', 'municipality_id' => Municipality::where('key', 9)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28937', 'locality' => '', 'municipality_id' => Municipality::where('key', 9)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28938', 'locality' => '', 'municipality_id' => Municipality::where('key', 9)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28940', 'locality' => '', 'municipality_id' => Municipality::where('key', 9)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28944', 'locality' => '', 'municipality_id' => Municipality::where('key', 9)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28945', 'locality' => '', 'municipality_id' => Municipality::where('key', 9)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28947', 'locality' => '', 'municipality_id' => Municipality::where('key', 9)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28950', 'locality' => '', 'municipality_id' => Municipality::where('key', 10)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28952', 'locality' => '', 'municipality_id' => Municipality::where('key', 10)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28955', 'locality' => '', 'municipality_id' => Municipality::where('key', 10)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28958', 'locality' => '', 'municipality_id' => Municipality::where('key', 10)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28959', 'locality' => '', 'municipality_id' => Municipality::where('key', 10)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28960', 'locality' => '', 'municipality_id' => Municipality::where('key', 10)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28963', 'locality' => '', 'municipality_id' => Municipality::where('key', 10)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28965', 'locality' => '', 'municipality_id' => Municipality::where('key', 10)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28968', 'locality' => '', 'municipality_id' => Municipality::where('key', 10)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28970', 'locality' => 'Ciudad de Villa de Álvarez', 'municipality_id' => Municipality::where('key', 10)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28973', 'locality' => 'Ciudad de Villa de Álvarez', 'municipality_id' => Municipality::where('key', 10)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28974', 'locality' => 'Ciudad de Villa de Álvarez', 'municipality_id' => Municipality::where('key', 10)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28975', 'locality' => 'Ciudad de Villa de Álvarez', 'municipality_id' => Municipality::where('key', 10)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28976', 'locality' => 'Ciudad de Villa de Álvarez', 'municipality_id' => Municipality::where('key', 10)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28977', 'locality' => 'Ciudad de Villa de Álvarez', 'municipality_id' => Municipality::where('key', 10)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28978', 'locality' => 'Ciudad de Villa de Álvarez', 'municipality_id' => Municipality::where('key', 10)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28979', 'locality' => 'Ciudad de Villa de Álvarez', 'municipality_id' => Municipality::where('key', 10)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28980', 'locality' => 'Ciudad de Villa de Álvarez', 'municipality_id' => Municipality::where('key', 10)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28982', 'locality' => 'Ciudad de Villa de Álvarez', 'municipality_id' => Municipality::where('key', 10)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28983', 'locality' => 'Ciudad de Villa de Álvarez', 'municipality_id' => Municipality::where('key', 10)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28984', 'locality' => 'Ciudad de Villa de Álvarez', 'municipality_id' => Municipality::where('key', 10)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28985', 'locality' => 'Ciudad de Villa de Álvarez', 'municipality_id' => Municipality::where('key', 10)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28986', 'locality' => 'Ciudad de Villa de Álvarez', 'municipality_id' => Municipality::where('key', 10)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28987', 'locality' => 'Ciudad de Villa de Álvarez', 'municipality_id' => Municipality::where('key', 10)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28988', 'locality' => 'Ciudad de Villa de Álvarez', 'municipality_id' => Municipality::where('key', 10)->where('state_id', 6)->first()->id , 'state_id' => 6],
            [ 'zip_code' => '28989', 'locality' => 'Ciudad de Villa de Álvarez', 'municipality_id' => Municipality::where('key', 10)->where('state_id', 6)->first()->id , 'state_id' => 6],
        ];

        ZipCode::insert($zipCodes);
        unset($zipCodes);
    }
}
