<?php

namespace Database\Seeders;

use App\Models\ZipCode;
use App\Models\Municipality;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class NayaritZipCodesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $zipCodes = [
            [ 'zip_code' => '63000', 'locality' => 'Tepic', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63010', 'locality' => 'Tepic', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63018', 'locality' => 'Tepic', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63019', 'locality' => 'Tepic', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63020', 'locality' => 'Tepic', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63021', 'locality' => 'Tepic', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63022', 'locality' => 'Tepic', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63023', 'locality' => 'Tepic', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63030', 'locality' => 'Tepic', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63035', 'locality' => 'Tepic', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63037', 'locality' => 'Tepic', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63038', 'locality' => 'Tepic', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63039', 'locality' => 'Tepic', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63040', 'locality' => 'Tepic', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63050', 'locality' => 'Tepic', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63058', 'locality' => 'Tepic', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63059', 'locality' => 'Tepic', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63060', 'locality' => 'Tepic', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63061', 'locality' => 'Tepic', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63062', 'locality' => 'Tepic', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63066', 'locality' => 'Tepic', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63067', 'locality' => 'Tepic', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63068', 'locality' => 'Tepic', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63069', 'locality' => 'Tepic', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63070', 'locality' => 'Tepic', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63080', 'locality' => 'Tepic', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63081', 'locality' => 'Tepic', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63082', 'locality' => 'Tepic', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63083', 'locality' => 'Tepic', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63084', 'locality' => 'Tepic', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63088', 'locality' => 'Tepic', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63089', 'locality' => 'Tepic', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63100', 'locality' => 'Tepic', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63109', 'locality' => 'Tepic', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63110', 'locality' => 'Tepic', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63114', 'locality' => 'Tepic', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63115', 'locality' => 'Tepic', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63116', 'locality' => 'Tepic', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63117', 'locality' => 'Tepic', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63119', 'locality' => 'Tepic', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63120', 'locality' => 'Tepic', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63128', 'locality' => 'Tepic', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63129', 'locality' => 'Tepic', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63130', 'locality' => 'Tepic', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63135', 'locality' => 'Tepic', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63136', 'locality' => 'Tepic', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63137', 'locality' => 'Tepic', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63138', 'locality' => 'Tepic', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63139', 'locality' => 'Tepic', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63150', 'locality' => 'Tepic', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63155', 'locality' => 'Tepic', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63156', 'locality' => 'Tepic', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63157', 'locality' => 'Tepic', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63158', 'locality' => 'Tepic', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63159', 'locality' => 'Tepic', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63160', 'locality' => 'Tepic', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63163', 'locality' => 'Tepic', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63164', 'locality' => 'Tepic', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63165', 'locality' => 'Tepic', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63166', 'locality' => 'Tepic', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63167', 'locality' => 'Tepic', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63168', 'locality' => 'Tepic', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63169', 'locality' => 'Tepic', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63170', 'locality' => 'Tepic', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63172', 'locality' => 'Tepic', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63173', 'locality' => 'Tepic', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63174', 'locality' => 'Tepic', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63175', 'locality' => 'Tepic', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63176', 'locality' => 'Tepic', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63177', 'locality' => 'Tepic', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63178', 'locality' => 'Tepic', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63179', 'locality' => 'Tepic', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63180', 'locality' => 'Tepic', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63183', 'locality' => 'Tepic', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63184', 'locality' => 'Tepic', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63185', 'locality' => 'Tepic', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63186', 'locality' => 'Tepic', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63190', 'locality' => 'Tepic', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63193', 'locality' => 'Tepic', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63194', 'locality' => 'Tepic', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63195', 'locality' => 'Tepic', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63196', 'locality' => 'Tepic', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63197', 'locality' => 'Tepic', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63198', 'locality' => 'Tepic', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63199', 'locality' => 'Tepic', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63200', 'locality' => 'Tuxpan', 'municipality_id' => Municipality::where('key', 18)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63202', 'locality' => 'Tuxpan', 'municipality_id' => Municipality::where('key', 18)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63203', 'locality' => 'Tuxpan', 'municipality_id' => Municipality::where('key', 18)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63205', 'locality' => 'Tuxpan', 'municipality_id' => Municipality::where('key', 18)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63207', 'locality' => 'Tuxpan', 'municipality_id' => Municipality::where('key', 18)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63225', 'locality' => 'Tuxpan', 'municipality_id' => Municipality::where('key', 18)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63227', 'locality' => 'Tuxpan', 'municipality_id' => Municipality::where('key', 18)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63300', 'locality' => 'Santiago Ixcuintla', 'municipality_id' => Municipality::where('key', 15)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63310', 'locality' => 'Santiago Ixcuintla', 'municipality_id' => Municipality::where('key', 15)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63311', 'locality' => 'Santiago Ixcuintla', 'municipality_id' => Municipality::where('key', 15)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63312', 'locality' => 'Santiago Ixcuintla', 'municipality_id' => Municipality::where('key', 15)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63313', 'locality' => 'Santiago Ixcuintla', 'municipality_id' => Municipality::where('key', 15)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63320', 'locality' => 'Santiago Ixcuintla', 'municipality_id' => Municipality::where('key', 15)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63321', 'locality' => 'Santiago Ixcuintla', 'municipality_id' => Municipality::where('key', 15)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63330', 'locality' => 'Santiago Ixcuintla', 'municipality_id' => Municipality::where('key', 15)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63340', 'locality' => 'Santiago Ixcuintla', 'municipality_id' => Municipality::where('key', 15)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63341', 'locality' => 'Santiago Ixcuintla', 'municipality_id' => Municipality::where('key', 15)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63350', 'locality' => 'Santiago Ixcuintla', 'municipality_id' => Municipality::where('key', 15)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63351', 'locality' => 'Santiago Ixcuintla', 'municipality_id' => Municipality::where('key', 15)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63352', 'locality' => 'Santiago Ixcuintla', 'municipality_id' => Municipality::where('key', 15)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63360', 'locality' => 'Santiago Ixcuintla', 'municipality_id' => Municipality::where('key', 15)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63380', 'locality' => '', 'municipality_id' => Municipality::where('key', 15)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63383', 'locality' => '', 'municipality_id' => Municipality::where('key', 15)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63384', 'locality' => '', 'municipality_id' => Municipality::where('key', 15)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63385', 'locality' => '', 'municipality_id' => Municipality::where('key', 15)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63386', 'locality' => '', 'municipality_id' => Municipality::where('key', 15)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63400', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63403', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63404', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63405', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63406', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63407', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63408', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63409', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63410', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63412', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63413', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63414', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63415', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63416', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63420', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63421', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63423', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63424', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63425', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63426', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63427', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63429', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63430', 'locality' => 'Acaponeta', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63434', 'locality' => 'Acaponeta', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63435', 'locality' => 'Acaponeta', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63436', 'locality' => 'Acaponeta', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63437', 'locality' => 'Acaponeta', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63438', 'locality' => 'Acaponeta', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63440', 'locality' => '', 'municipality_id' => Municipality::where('key', 16)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63443', 'locality' => '', 'municipality_id' => Municipality::where('key', 16)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63444', 'locality' => '', 'municipality_id' => Municipality::where('key', 16)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63445', 'locality' => '', 'municipality_id' => Municipality::where('key', 16)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63446', 'locality' => '', 'municipality_id' => Municipality::where('key', 16)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63447', 'locality' => '', 'municipality_id' => Municipality::where('key', 16)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63449', 'locality' => '', 'municipality_id' => Municipality::where('key', 16)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63450', 'locality' => 'Tecuala', 'municipality_id' => Municipality::where('key', 16)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63453', 'locality' => 'Tecuala', 'municipality_id' => Municipality::where('key', 16)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63454', 'locality' => 'Tecuala', 'municipality_id' => Municipality::where('key', 16)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63455', 'locality' => 'Tecuala', 'municipality_id' => Municipality::where('key', 16)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63456', 'locality' => '', 'municipality_id' => Municipality::where('key', 16)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63457', 'locality' => '', 'municipality_id' => Municipality::where('key', 16)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63458', 'locality' => '', 'municipality_id' => Municipality::where('key', 16)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63459', 'locality' => '', 'municipality_id' => Municipality::where('key', 16)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63460', 'locality' => '', 'municipality_id' => Municipality::where('key', 16)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63463', 'locality' => '', 'municipality_id' => Municipality::where('key', 16)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63464', 'locality' => '', 'municipality_id' => Municipality::where('key', 16)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63466', 'locality' => '', 'municipality_id' => Municipality::where('key', 16)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63470', 'locality' => '', 'municipality_id' => Municipality::where('key', 16)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63480', 'locality' => '', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63484', 'locality' => '', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63485', 'locality' => '', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63486', 'locality' => '', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63487', 'locality' => '', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63489', 'locality' => '', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63494', 'locality' => '', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63495', 'locality' => '', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63496', 'locality' => '', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63497', 'locality' => '', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63498', 'locality' => '', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63499', 'locality' => '', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63500', 'locality' => 'Francisco I. Madero (Puga)', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63501', 'locality' => '', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63502', 'locality' => '', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63503', 'locality' => '', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63504', 'locality' => '', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63505', 'locality' => '', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63506', 'locality' => '', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63507', 'locality' => '', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63508', 'locality' => '', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63509', 'locality' => '', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63510', 'locality' => '', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63511', 'locality' => '', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63512', 'locality' => '', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63513', 'locality' => '', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63514', 'locality' => '', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63515', 'locality' => '', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63516', 'locality' => '', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63517', 'locality' => '', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63518', 'locality' => '', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63519', 'locality' => '', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63520', 'locality' => '', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63522', 'locality' => '', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63523', 'locality' => '', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63524', 'locality' => '', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63526', 'locality' => '', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63527', 'locality' => '', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63528', 'locality' => '', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63529', 'locality' => '', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63530', 'locality' => '', 'municipality_id' => Municipality::where('key', 9)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63533', 'locality' => '', 'municipality_id' => Municipality::where('key', 9)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63534', 'locality' => '', 'municipality_id' => Municipality::where('key', 9)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63535', 'locality' => '', 'municipality_id' => Municipality::where('key', 9)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63536', 'locality' => '', 'municipality_id' => Municipality::where('key', 9)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63537', 'locality' => '', 'municipality_id' => Municipality::where('key', 9)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63538', 'locality' => '', 'municipality_id' => Municipality::where('key', 9)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63539', 'locality' => '', 'municipality_id' => Municipality::where('key', 9)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63540', 'locality' => '', 'municipality_id' => Municipality::where('key', 9)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63543', 'locality' => '', 'municipality_id' => Municipality::where('key', 9)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63544', 'locality' => '', 'municipality_id' => Municipality::where('key', 9)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63545', 'locality' => '', 'municipality_id' => Municipality::where('key', 9)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63546', 'locality' => '', 'municipality_id' => Municipality::where('key', 9)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63547', 'locality' => '', 'municipality_id' => Municipality::where('key', 9)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63548', 'locality' => '', 'municipality_id' => Municipality::where('key', 9)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63549', 'locality' => '', 'municipality_id' => Municipality::where('key', 9)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63550', 'locality' => 'Villa Hidalgo (El Nuevo)', 'municipality_id' => Municipality::where('key', 15)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63552', 'locality' => '', 'municipality_id' => Municipality::where('key', 15)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63553', 'locality' => '', 'municipality_id' => Municipality::where('key', 15)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63554', 'locality' => '', 'municipality_id' => Municipality::where('key', 15)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63555', 'locality' => '', 'municipality_id' => Municipality::where('key', 15)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63556', 'locality' => '', 'municipality_id' => Municipality::where('key', 15)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63557', 'locality' => '', 'municipality_id' => Municipality::where('key', 15)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63558', 'locality' => '', 'municipality_id' => Municipality::where('key', 15)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63559', 'locality' => '', 'municipality_id' => Municipality::where('key', 15)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63560', 'locality' => '', 'municipality_id' => Municipality::where('key', 15)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63561', 'locality' => '', 'municipality_id' => Municipality::where('key', 15)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63562', 'locality' => '', 'municipality_id' => Municipality::where('key', 15)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63563', 'locality' => '', 'municipality_id' => Municipality::where('key', 15)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63564', 'locality' => '', 'municipality_id' => Municipality::where('key', 15)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63565', 'locality' => '', 'municipality_id' => Municipality::where('key', 15)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63567', 'locality' => '', 'municipality_id' => Municipality::where('key', 15)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63568', 'locality' => '', 'municipality_id' => Municipality::where('key', 15)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63570', 'locality' => '', 'municipality_id' => Municipality::where('key', 15)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63573', 'locality' => '', 'municipality_id' => Municipality::where('key', 15)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63575', 'locality' => '', 'municipality_id' => Municipality::where('key', 15)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63576', 'locality' => '', 'municipality_id' => Municipality::where('key', 15)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63577', 'locality' => '', 'municipality_id' => Municipality::where('key', 15)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63578', 'locality' => '', 'municipality_id' => Municipality::where('key', 15)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63579', 'locality' => '', 'municipality_id' => Municipality::where('key', 15)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63580', 'locality' => '', 'municipality_id' => Municipality::where('key', 19)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63582', 'locality' => '', 'municipality_id' => Municipality::where('key', 19)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63583', 'locality' => '', 'municipality_id' => Municipality::where('key', 19)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63584', 'locality' => '', 'municipality_id' => Municipality::where('key', 19)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63586', 'locality' => '', 'municipality_id' => Municipality::where('key', 19)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63587', 'locality' => '', 'municipality_id' => Municipality::where('key', 19)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63590', 'locality' => '', 'municipality_id' => Municipality::where('key', 19)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63593', 'locality' => '', 'municipality_id' => Municipality::where('key', 19)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63594', 'locality' => '', 'municipality_id' => Municipality::where('key', 19)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63595', 'locality' => '', 'municipality_id' => Municipality::where('key', 19)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63596', 'locality' => '', 'municipality_id' => Municipality::where('key', 19)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63597', 'locality' => '', 'municipality_id' => Municipality::where('key', 19)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63600', 'locality' => '', 'municipality_id' => Municipality::where('key', 11)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63603', 'locality' => '', 'municipality_id' => Municipality::where('key', 11)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63604', 'locality' => '', 'municipality_id' => Municipality::where('key', 11)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63605', 'locality' => '', 'municipality_id' => Municipality::where('key', 11)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63606', 'locality' => '', 'municipality_id' => Municipality::where('key', 11)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63607', 'locality' => '', 'municipality_id' => Municipality::where('key', 11)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63610', 'locality' => '', 'municipality_id' => Municipality::where('key', 11)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63613', 'locality' => '', 'municipality_id' => Municipality::where('key', 11)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63614', 'locality' => '', 'municipality_id' => Municipality::where('key', 11)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63615', 'locality' => '', 'municipality_id' => Municipality::where('key', 11)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63616', 'locality' => '', 'municipality_id' => Municipality::where('key', 11)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63617', 'locality' => '', 'municipality_id' => Municipality::where('key', 11)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63618', 'locality' => '', 'municipality_id' => Municipality::where('key', 11)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63619', 'locality' => '', 'municipality_id' => Municipality::where('key', 11)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63620', 'locality' => 'Ruíz', 'municipality_id' => Municipality::where('key', 11)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63622', 'locality' => 'Ruíz', 'municipality_id' => Municipality::where('key', 11)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63623', 'locality' => 'Ruíz', 'municipality_id' => Municipality::where('key', 11)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63625', 'locality' => 'Ruíz', 'municipality_id' => Municipality::where('key', 11)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63626', 'locality' => 'Ruíz', 'municipality_id' => Municipality::where('key', 11)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63627', 'locality' => 'Ruíz', 'municipality_id' => Municipality::where('key', 11)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63628', 'locality' => 'Ruíz', 'municipality_id' => Municipality::where('key', 11)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63630', 'locality' => '', 'municipality_id' => Municipality::where('key', 10)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63633', 'locality' => '', 'municipality_id' => Municipality::where('key', 10)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63634', 'locality' => '', 'municipality_id' => Municipality::where('key', 10)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63635', 'locality' => '', 'municipality_id' => Municipality::where('key', 10)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63636', 'locality' => '', 'municipality_id' => Municipality::where('key', 10)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63637', 'locality' => '', 'municipality_id' => Municipality::where('key', 10)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63638', 'locality' => '', 'municipality_id' => Municipality::where('key', 10)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63640', 'locality' => '', 'municipality_id' => Municipality::where('key', 10)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63643', 'locality' => '', 'municipality_id' => Municipality::where('key', 10)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63644', 'locality' => '', 'municipality_id' => Municipality::where('key', 10)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63645', 'locality' => '', 'municipality_id' => Municipality::where('key', 10)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63646', 'locality' => '', 'municipality_id' => Municipality::where('key', 10)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63648', 'locality' => '', 'municipality_id' => Municipality::where('key', 10)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63650', 'locality' => '', 'municipality_id' => Municipality::where('key', 10)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63652', 'locality' => '', 'municipality_id' => Municipality::where('key', 10)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63655', 'locality' => '', 'municipality_id' => Municipality::where('key', 10)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63656', 'locality' => '', 'municipality_id' => Municipality::where('key', 10)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63657', 'locality' => '', 'municipality_id' => Municipality::where('key', 10)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63658', 'locality' => '', 'municipality_id' => Municipality::where('key', 10)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63660', 'locality' => '', 'municipality_id' => Municipality::where('key', 18)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63670', 'locality' => '', 'municipality_id' => Municipality::where('key', 18)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63700', 'locality' => 'Compostela', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63702', 'locality' => 'Compostela', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63703', 'locality' => 'Compostela', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63704', 'locality' => 'Compostela', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63705', 'locality' => 'Compostela', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63706', 'locality' => '', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63707', 'locality' => '', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63708', 'locality' => '', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63709', 'locality' => '', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63710', 'locality' => '', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63713', 'locality' => '', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63714', 'locality' => '', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63715', 'locality' => 'Las Varas', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63717', 'locality' => '', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63719', 'locality' => '', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63720', 'locality' => 'La Peñita de Jaltemba', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63722', 'locality' => '', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63723', 'locality' => '', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63724', 'locality' => '', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63726', 'locality' => '', 'municipality_id' => Municipality::where('key', 20)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63728', 'locality' => '', 'municipality_id' => Municipality::where('key', 20)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63729', 'locality' => '', 'municipality_id' => Municipality::where('key', 20)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63730', 'locality' => '', 'municipality_id' => Municipality::where('key', 20)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63732', 'locality' => 'Bucerías', 'municipality_id' => Municipality::where('key', 20)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63734', 'locality' => '', 'municipality_id' => Municipality::where('key', 20)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63735', 'locality' => '', 'municipality_id' => Municipality::where('key', 20)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63736', 'locality' => '', 'municipality_id' => Municipality::where('key', 20)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63737', 'locality' => '', 'municipality_id' => Municipality::where('key', 20)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63738', 'locality' => '', 'municipality_id' => Municipality::where('key', 20)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63739', 'locality' => '', 'municipality_id' => Municipality::where('key', 20)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63740', 'locality' => 'San Blas', 'municipality_id' => Municipality::where('key', 12)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63742', 'locality' => 'San Blas', 'municipality_id' => Municipality::where('key', 12)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63743', 'locality' => 'San Blas', 'municipality_id' => Municipality::where('key', 12)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63744', 'locality' => 'San Blas', 'municipality_id' => Municipality::where('key', 12)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63745', 'locality' => '', 'municipality_id' => Municipality::where('key', 12)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63750', 'locality' => '', 'municipality_id' => Municipality::where('key', 12)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63751', 'locality' => '', 'municipality_id' => Municipality::where('key', 12)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63753', 'locality' => '', 'municipality_id' => Municipality::where('key', 12)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63754', 'locality' => '', 'municipality_id' => Municipality::where('key', 12)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63755', 'locality' => '', 'municipality_id' => Municipality::where('key', 12)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63756', 'locality' => '', 'municipality_id' => Municipality::where('key', 12)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63757', 'locality' => '', 'municipality_id' => Municipality::where('key', 12)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63758', 'locality' => '', 'municipality_id' => Municipality::where('key', 12)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63760', 'locality' => '', 'municipality_id' => Municipality::where('key', 12)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63762', 'locality' => '', 'municipality_id' => Municipality::where('key', 12)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63763', 'locality' => '', 'municipality_id' => Municipality::where('key', 12)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63764', 'locality' => '', 'municipality_id' => Municipality::where('key', 12)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63765', 'locality' => '', 'municipality_id' => Municipality::where('key', 12)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63766', 'locality' => '', 'municipality_id' => Municipality::where('key', 12)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63770', 'locality' => '', 'municipality_id' => Municipality::where('key', 12)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63771', 'locality' => '', 'municipality_id' => Municipality::where('key', 12)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63772', 'locality' => '', 'municipality_id' => Municipality::where('key', 12)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63773', 'locality' => '', 'municipality_id' => Municipality::where('key', 12)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63774', 'locality' => '', 'municipality_id' => Municipality::where('key', 12)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63775', 'locality' => '', 'municipality_id' => Municipality::where('key', 12)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63776', 'locality' => '', 'municipality_id' => Municipality::where('key', 12)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63777', 'locality' => '', 'municipality_id' => Municipality::where('key', 12)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63779', 'locality' => '', 'municipality_id' => Municipality::where('key', 12)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63780', 'locality' => 'Xalisco', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63782', 'locality' => 'Xalisco', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63783', 'locality' => 'Xalisco', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63784', 'locality' => 'Xalisco', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63785', 'locality' => 'Xalisco', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63786', 'locality' => 'Xalisco', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63787', 'locality' => 'Xalisco', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63788', 'locality' => 'Xalisco', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63790', 'locality' => '', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63792', 'locality' => '', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63793', 'locality' => '', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63794', 'locality' => '', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63795', 'locality' => '', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63797', 'locality' => '', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63799', 'locality' => '', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63800', 'locality' => 'San Pedro Lagunillas', 'municipality_id' => Municipality::where('key', 13)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63804', 'locality' => '', 'municipality_id' => Municipality::where('key', 13)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63809', 'locality' => '', 'municipality_id' => Municipality::where('key', 13)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63810', 'locality' => 'San Pedro Lagunillas', 'municipality_id' => Municipality::where('key', 13)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63820', 'locality' => '', 'municipality_id' => Municipality::where('key', 13)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63826', 'locality' => '', 'municipality_id' => Municipality::where('key', 13)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63830', 'locality' => '', 'municipality_id' => Municipality::where('key', 14)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63833', 'locality' => '', 'municipality_id' => Municipality::where('key', 14)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63834', 'locality' => '', 'municipality_id' => Municipality::where('key', 14)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63835', 'locality' => '', 'municipality_id' => Municipality::where('key', 14)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63836', 'locality' => '', 'municipality_id' => Municipality::where('key', 14)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63837', 'locality' => '', 'municipality_id' => Municipality::where('key', 14)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63840', 'locality' => '', 'municipality_id' => Municipality::where('key', 14)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63843', 'locality' => '', 'municipality_id' => Municipality::where('key', 14)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63844', 'locality' => '', 'municipality_id' => Municipality::where('key', 14)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63845', 'locality' => '', 'municipality_id' => Municipality::where('key', 14)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63850', 'locality' => '', 'municipality_id' => Municipality::where('key', 14)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63853', 'locality' => '', 'municipality_id' => Municipality::where('key', 14)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63854', 'locality' => '', 'municipality_id' => Municipality::where('key', 14)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63856', 'locality' => '', 'municipality_id' => Municipality::where('key', 14)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63865', 'locality' => '', 'municipality_id' => Municipality::where('key', 14)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63866', 'locality' => '', 'municipality_id' => Municipality::where('key', 14)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63867', 'locality' => '', 'municipality_id' => Municipality::where('key', 14)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63870', 'locality' => '', 'municipality_id' => Municipality::where('key', 14)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63874', 'locality' => '', 'municipality_id' => Municipality::where('key', 14)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63880', 'locality' => '', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63883', 'locality' => '', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63885', 'locality' => '', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63886', 'locality' => '', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63887', 'locality' => '', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63890', 'locality' => 'Jala', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63893', 'locality' => 'Jala', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63894', 'locality' => 'Jala', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63895', 'locality' => 'Jala', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63897', 'locality' => '', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63899', 'locality' => '', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63900', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63904', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63905', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63910', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63911', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63913', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63914', 'locality' => 'Ahuacatlán', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63915', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63920', 'locality' => 'Ahuacatlán', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63923', 'locality' => 'Ahuacatlán', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63925', 'locality' => 'Ahuacatlán', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63927', 'locality' => 'Ahuacatlán', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63928', 'locality' => 'Ahuacatlán', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63930', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63935', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63938', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63940', 'locality' => '', 'municipality_id' => Municipality::where('key', 6)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63944', 'locality' => '', 'municipality_id' => Municipality::where('key', 6)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63945', 'locality' => '', 'municipality_id' => Municipality::where('key', 6)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63946', 'locality' => '', 'municipality_id' => Municipality::where('key', 6)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63947', 'locality' => '', 'municipality_id' => Municipality::where('key', 6)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63950', 'locality' => 'Ixtlán del Río', 'municipality_id' => Municipality::where('key', 6)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63953', 'locality' => 'Ixtlán del Río', 'municipality_id' => Municipality::where('key', 6)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63954', 'locality' => 'Ixtlán del Río', 'municipality_id' => Municipality::where('key', 6)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63955', 'locality' => 'Ixtlán del Río', 'municipality_id' => Municipality::where('key', 6)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63956', 'locality' => 'Ixtlán del Río', 'municipality_id' => Municipality::where('key', 6)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63957', 'locality' => 'Ixtlán del Río', 'municipality_id' => Municipality::where('key', 6)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63958', 'locality' => 'Ixtlán del Río', 'municipality_id' => Municipality::where('key', 6)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63959', 'locality' => 'Ixtlán del Río', 'municipality_id' => Municipality::where('key', 6)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63960', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63963', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63967', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63968', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63969', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63970', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63973', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63974', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63975', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63980', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63985', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63990', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 18)->first()->id , 'state_id' => 18],
            [ 'zip_code' => '63996', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 18)->first()->id , 'state_id' => 18],
        ];

        ZipCode::insert($zipCodes);
        unset($zipCodes);
    }
}
