<?php

namespace Database\Seeders;

use App\Models\ZipCode;
use App\Models\Municipality;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class QueretaroZipCodesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $zipCodes = [
            [ 'zip_code' => '76000', 'locality' => 'Santiago de Querétaro', 'municipality_id' => Municipality::where('key', 14)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76010', 'locality' => 'Santiago de Querétaro', 'municipality_id' => Municipality::where('key', 14)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76017', 'locality' => 'Santiago de Querétaro', 'municipality_id' => Municipality::where('key', 14)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76020', 'locality' => 'Santiago de Querétaro', 'municipality_id' => Municipality::where('key', 14)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76024', 'locality' => 'Santiago de Querétaro', 'municipality_id' => Municipality::where('key', 14)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76025', 'locality' => 'Santiago de Querétaro', 'municipality_id' => Municipality::where('key', 14)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76026', 'locality' => 'Santiago de Querétaro', 'municipality_id' => Municipality::where('key', 14)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76027', 'locality' => 'Santiago de Querétaro', 'municipality_id' => Municipality::where('key', 14)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76028', 'locality' => 'Santiago de Querétaro', 'municipality_id' => Municipality::where('key', 14)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76030', 'locality' => 'Santiago de Querétaro', 'municipality_id' => Municipality::where('key', 14)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76036', 'locality' => 'Santiago de Querétaro', 'municipality_id' => Municipality::where('key', 14)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76037', 'locality' => 'Santiago de Querétaro', 'municipality_id' => Municipality::where('key', 14)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76040', 'locality' => 'Santiago de Querétaro', 'municipality_id' => Municipality::where('key', 14)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76046', 'locality' => 'Santiago de Querétaro', 'municipality_id' => Municipality::where('key', 14)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76047', 'locality' => 'Santiago de Querétaro', 'municipality_id' => Municipality::where('key', 14)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76048', 'locality' => 'Santiago de Querétaro', 'municipality_id' => Municipality::where('key', 14)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76049', 'locality' => 'Santiago de Querétaro', 'municipality_id' => Municipality::where('key', 14)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76050', 'locality' => 'Santiago de Querétaro', 'municipality_id' => Municipality::where('key', 14)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76057', 'locality' => 'Santiago de Querétaro', 'municipality_id' => Municipality::where('key', 14)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76058', 'locality' => 'Santiago de Querétaro', 'municipality_id' => Municipality::where('key', 14)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76059', 'locality' => 'Santiago de Querétaro', 'municipality_id' => Municipality::where('key', 14)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76060', 'locality' => 'Santiago de Querétaro', 'municipality_id' => Municipality::where('key', 14)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76063', 'locality' => 'Santiago de Querétaro', 'municipality_id' => Municipality::where('key', 14)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76067', 'locality' => 'Santiago de Querétaro', 'municipality_id' => Municipality::where('key', 14)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76069', 'locality' => 'Santiago de Querétaro', 'municipality_id' => Municipality::where('key', 14)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76070', 'locality' => 'Santiago de Querétaro', 'municipality_id' => Municipality::where('key', 14)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76074', 'locality' => 'Santiago de Querétaro', 'municipality_id' => Municipality::where('key', 14)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76078', 'locality' => 'Santiago de Querétaro', 'municipality_id' => Municipality::where('key', 14)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76079', 'locality' => 'Santiago de Querétaro', 'municipality_id' => Municipality::where('key', 14)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76080', 'locality' => 'Santiago de Querétaro', 'municipality_id' => Municipality::where('key', 14)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76085', 'locality' => 'Santiago de Querétaro', 'municipality_id' => Municipality::where('key', 14)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76086', 'locality' => 'Santiago de Querétaro', 'municipality_id' => Municipality::where('key', 14)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76087', 'locality' => 'Santiago de Querétaro', 'municipality_id' => Municipality::where('key', 14)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76090', 'locality' => 'Santiago de Querétaro', 'municipality_id' => Municipality::where('key', 14)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76093', 'locality' => 'Santiago de Querétaro', 'municipality_id' => Municipality::where('key', 14)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76099', 'locality' => 'Santiago de Querétaro', 'municipality_id' => Municipality::where('key', 14)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76100', 'locality' => 'Santiago de Querétaro', 'municipality_id' => Municipality::where('key', 14)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76110', 'locality' => 'Santiago de Querétaro', 'municipality_id' => Municipality::where('key', 14)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76113', 'locality' => 'Santiago de Querétaro', 'municipality_id' => Municipality::where('key', 14)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76114', 'locality' => 'Santiago de Querétaro', 'municipality_id' => Municipality::where('key', 14)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76115', 'locality' => 'Santiago de Querétaro', 'municipality_id' => Municipality::where('key', 14)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76116', 'locality' => 'Santiago de Querétaro', 'municipality_id' => Municipality::where('key', 14)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76117', 'locality' => 'Santiago de Querétaro', 'municipality_id' => Municipality::where('key', 14)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76118', 'locality' => 'Santiago de Querétaro', 'municipality_id' => Municipality::where('key', 14)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76120', 'locality' => 'Santiago de Querétaro', 'municipality_id' => Municipality::where('key', 14)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76121', 'locality' => 'Santiago de Querétaro', 'municipality_id' => Municipality::where('key', 14)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76125', 'locality' => 'Santiago de Querétaro', 'municipality_id' => Municipality::where('key', 14)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76127', 'locality' => 'Santiago de Querétaro', 'municipality_id' => Municipality::where('key', 14)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76130', 'locality' => 'Santiago de Querétaro', 'municipality_id' => Municipality::where('key', 14)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76134', 'locality' => 'Santiago de Querétaro', 'municipality_id' => Municipality::where('key', 14)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76135', 'locality' => 'Santiago de Querétaro', 'municipality_id' => Municipality::where('key', 14)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76136', 'locality' => 'Santiago de Querétaro', 'municipality_id' => Municipality::where('key', 14)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76137', 'locality' => 'Santiago de Querétaro', 'municipality_id' => Municipality::where('key', 14)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76138', 'locality' => 'Santiago de Querétaro', 'municipality_id' => Municipality::where('key', 14)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76139', 'locality' => 'Santiago de Querétaro', 'municipality_id' => Municipality::where('key', 14)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76140', 'locality' => 'Santiago de Querétaro', 'municipality_id' => Municipality::where('key', 14)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76144', 'locality' => 'Santiago de Querétaro', 'municipality_id' => Municipality::where('key', 14)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76146', 'locality' => 'Santiago de Querétaro', 'municipality_id' => Municipality::where('key', 14)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76147', 'locality' => 'Santiago de Querétaro', 'municipality_id' => Municipality::where('key', 14)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76148', 'locality' => 'Santiago de Querétaro', 'municipality_id' => Municipality::where('key', 14)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76149', 'locality' => 'Santiago de Querétaro', 'municipality_id' => Municipality::where('key', 14)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76150', 'locality' => 'Santiago de Querétaro', 'municipality_id' => Municipality::where('key', 14)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76154', 'locality' => 'Santiago de Querétaro', 'municipality_id' => Municipality::where('key', 14)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76155', 'locality' => 'Santiago de Querétaro', 'municipality_id' => Municipality::where('key', 14)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76156', 'locality' => 'Santiago de Querétaro', 'municipality_id' => Municipality::where('key', 14)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76157', 'locality' => 'Santiago de Querétaro', 'municipality_id' => Municipality::where('key', 14)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76158', 'locality' => 'Santiago de Querétaro', 'municipality_id' => Municipality::where('key', 14)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76159', 'locality' => 'Santiago de Querétaro', 'municipality_id' => Municipality::where('key', 14)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76160', 'locality' => 'Santiago de Querétaro', 'municipality_id' => Municipality::where('key', 14)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76164', 'locality' => 'Santiago de Querétaro', 'municipality_id' => Municipality::where('key', 14)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76165', 'locality' => 'Santiago de Querétaro', 'municipality_id' => Municipality::where('key', 14)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76166', 'locality' => 'Santiago de Querétaro', 'municipality_id' => Municipality::where('key', 14)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76168', 'locality' => 'Santiago de Querétaro', 'municipality_id' => Municipality::where('key', 14)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76169', 'locality' => 'Santiago de Querétaro', 'municipality_id' => Municipality::where('key', 14)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76170', 'locality' => 'Santiago de Querétaro', 'municipality_id' => Municipality::where('key', 14)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76175', 'locality' => 'Santiago de Querétaro', 'municipality_id' => Municipality::where('key', 14)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76176', 'locality' => 'Santiago de Querétaro', 'municipality_id' => Municipality::where('key', 14)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76177', 'locality' => 'Santiago de Querétaro', 'municipality_id' => Municipality::where('key', 14)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76178', 'locality' => 'Santiago de Querétaro', 'municipality_id' => Municipality::where('key', 14)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76179', 'locality' => 'Santiago de Querétaro', 'municipality_id' => Municipality::where('key', 14)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76180', 'locality' => 'Santiago de Querétaro', 'municipality_id' => Municipality::where('key', 14)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76185', 'locality' => 'Santiago de Querétaro', 'municipality_id' => Municipality::where('key', 14)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76190', 'locality' => 'Santiago de Querétaro', 'municipality_id' => Municipality::where('key', 14)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76197', 'locality' => 'Santiago de Querétaro', 'municipality_id' => Municipality::where('key', 14)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76199', 'locality' => 'Santiago de Querétaro', 'municipality_id' => Municipality::where('key', 14)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76210', 'locality' => '', 'municipality_id' => Municipality::where('key', 14)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76211', 'locality' => '', 'municipality_id' => Municipality::where('key', 14)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76212', 'locality' => '', 'municipality_id' => Municipality::where('key', 14)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76213', 'locality' => '', 'municipality_id' => Municipality::where('key', 14)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76214', 'locality' => '', 'municipality_id' => Municipality::where('key', 14)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76215', 'locality' => '', 'municipality_id' => Municipality::where('key', 14)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76216', 'locality' => '', 'municipality_id' => Municipality::where('key', 14)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76217', 'locality' => '', 'municipality_id' => Municipality::where('key', 14)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76218', 'locality' => '', 'municipality_id' => Municipality::where('key', 14)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76219', 'locality' => '', 'municipality_id' => Municipality::where('key', 14)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76220', 'locality' => '', 'municipality_id' => Municipality::where('key', 14)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76221', 'locality' => '', 'municipality_id' => Municipality::where('key', 14)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76223', 'locality' => '', 'municipality_id' => Municipality::where('key', 14)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76224', 'locality' => '', 'municipality_id' => Municipality::where('key', 14)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76225', 'locality' => '', 'municipality_id' => Municipality::where('key', 14)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76226', 'locality' => '', 'municipality_id' => Municipality::where('key', 14)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76227', 'locality' => '', 'municipality_id' => Municipality::where('key', 14)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76228', 'locality' => '', 'municipality_id' => Municipality::where('key', 14)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76229', 'locality' => '', 'municipality_id' => Municipality::where('key', 14)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76230', 'locality' => '', 'municipality_id' => Municipality::where('key', 14)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76233', 'locality' => '', 'municipality_id' => Municipality::where('key', 14)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76235', 'locality' => '', 'municipality_id' => Municipality::where('key', 14)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76237', 'locality' => '', 'municipality_id' => Municipality::where('key', 14)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76238', 'locality' => '', 'municipality_id' => Municipality::where('key', 14)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76240', 'locality' => '', 'municipality_id' => Municipality::where('key', 11)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76243', 'locality' => '', 'municipality_id' => Municipality::where('key', 11)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76244', 'locality' => '', 'municipality_id' => Municipality::where('key', 11)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76245', 'locality' => '', 'municipality_id' => Municipality::where('key', 11)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76246', 'locality' => '', 'municipality_id' => Municipality::where('key', 11)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76247', 'locality' => '', 'municipality_id' => Municipality::where('key', 11)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76248', 'locality' => '', 'municipality_id' => Municipality::where('key', 11)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76249', 'locality' => '', 'municipality_id' => Municipality::where('key', 11)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76250', 'locality' => '', 'municipality_id' => Municipality::where('key', 11)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76251', 'locality' => '', 'municipality_id' => Municipality::where('key', 11)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76252', 'locality' => '', 'municipality_id' => Municipality::where('key', 11)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76253', 'locality' => '', 'municipality_id' => Municipality::where('key', 11)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76254', 'locality' => '', 'municipality_id' => Municipality::where('key', 11)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76255', 'locality' => '', 'municipality_id' => Municipality::where('key', 11)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76256', 'locality' => '', 'municipality_id' => Municipality::where('key', 11)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76257', 'locality' => '', 'municipality_id' => Municipality::where('key', 11)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76258', 'locality' => '', 'municipality_id' => Municipality::where('key', 11)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76259', 'locality' => '', 'municipality_id' => Municipality::where('key', 11)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76260', 'locality' => '', 'municipality_id' => Municipality::where('key', 11)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76261', 'locality' => '', 'municipality_id' => Municipality::where('key', 11)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76262', 'locality' => '', 'municipality_id' => Municipality::where('key', 11)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76263', 'locality' => '', 'municipality_id' => Municipality::where('key', 11)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76264', 'locality' => '', 'municipality_id' => Municipality::where('key', 11)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76265', 'locality' => '', 'municipality_id' => Municipality::where('key', 11)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76266', 'locality' => '', 'municipality_id' => Municipality::where('key', 11)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76267', 'locality' => '', 'municipality_id' => Municipality::where('key', 11)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76268', 'locality' => '', 'municipality_id' => Municipality::where('key', 11)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76269', 'locality' => '', 'municipality_id' => Municipality::where('key', 11)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76270', 'locality' => '', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76272', 'locality' => '', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76273', 'locality' => '', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76274', 'locality' => '', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76276', 'locality' => '', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76277', 'locality' => '', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76278', 'locality' => '', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76279', 'locality' => '', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76280', 'locality' => '', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76281', 'locality' => '', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76282', 'locality' => '', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76283', 'locality' => '', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76284', 'locality' => '', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76286', 'locality' => '', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76288', 'locality' => '', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76289', 'locality' => '', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76290', 'locality' => '', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76293', 'locality' => '', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76294', 'locality' => '', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76295', 'locality' => '', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76296', 'locality' => '', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76297', 'locality' => '', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76298', 'locality' => '', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76299', 'locality' => '', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76300', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76303', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76304', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76309', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76310', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76313', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76314', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76315', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76316', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76317', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76318', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76319', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76320', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76321', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76323', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76324', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76325', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76326', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76327', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76330', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76333', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76334', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76335', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76336', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76337', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76340', 'locality' => '', 'municipality_id' => Municipality::where('key', 9)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76342', 'locality' => '', 'municipality_id' => Municipality::where('key', 9)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76344', 'locality' => '', 'municipality_id' => Municipality::where('key', 9)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76345', 'locality' => '', 'municipality_id' => Municipality::where('key', 9)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76346', 'locality' => '', 'municipality_id' => Municipality::where('key', 9)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76347', 'locality' => '', 'municipality_id' => Municipality::where('key', 9)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76348', 'locality' => '', 'municipality_id' => Municipality::where('key', 9)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76350', 'locality' => '', 'municipality_id' => Municipality::where('key', 9)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76353', 'locality' => '', 'municipality_id' => Municipality::where('key', 9)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76354', 'locality' => '', 'municipality_id' => Municipality::where('key', 9)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76355', 'locality' => '', 'municipality_id' => Municipality::where('key', 9)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76356', 'locality' => '', 'municipality_id' => Municipality::where('key', 9)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76357', 'locality' => '', 'municipality_id' => Municipality::where('key', 9)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76358', 'locality' => '', 'municipality_id' => Municipality::where('key', 9)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76359', 'locality' => '', 'municipality_id' => Municipality::where('key', 9)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76360', 'locality' => '', 'municipality_id' => Municipality::where('key', 10)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76367', 'locality' => '', 'municipality_id' => Municipality::where('key', 10)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76368', 'locality' => '', 'municipality_id' => Municipality::where('key', 10)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76370', 'locality' => '', 'municipality_id' => Municipality::where('key', 10)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76372', 'locality' => '', 'municipality_id' => Municipality::where('key', 10)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76373', 'locality' => '', 'municipality_id' => Municipality::where('key', 10)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76378', 'locality' => '', 'municipality_id' => Municipality::where('key', 10)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76379', 'locality' => '', 'municipality_id' => Municipality::where('key', 10)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76380', 'locality' => '', 'municipality_id' => Municipality::where('key', 10)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76382', 'locality' => '', 'municipality_id' => Municipality::where('key', 10)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76383', 'locality' => '', 'municipality_id' => Municipality::where('key', 10)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76384', 'locality' => '', 'municipality_id' => Municipality::where('key', 10)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76385', 'locality' => '', 'municipality_id' => Municipality::where('key', 10)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76386', 'locality' => '', 'municipality_id' => Municipality::where('key', 10)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76388', 'locality' => '', 'municipality_id' => Municipality::where('key', 10)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76390', 'locality' => '', 'municipality_id' => Municipality::where('key', 10)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76392', 'locality' => '', 'municipality_id' => Municipality::where('key', 10)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76393', 'locality' => '', 'municipality_id' => Municipality::where('key', 10)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76394', 'locality' => '', 'municipality_id' => Municipality::where('key', 10)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76395', 'locality' => '', 'municipality_id' => Municipality::where('key', 10)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76396', 'locality' => '', 'municipality_id' => Municipality::where('key', 10)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76399', 'locality' => '', 'municipality_id' => Municipality::where('key', 10)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76400', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76401', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76402', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76410', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76411', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76413', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76414', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76417', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76420', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76421', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76424', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76425', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76426', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76427', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76434', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76436', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76440', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76450', 'locality' => '', 'municipality_id' => Municipality::where('key', 13)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76453', 'locality' => '', 'municipality_id' => Municipality::where('key', 13)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76454', 'locality' => '', 'municipality_id' => Municipality::where('key', 13)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76460', 'locality' => '', 'municipality_id' => Municipality::where('key', 13)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76463', 'locality' => '', 'municipality_id' => Municipality::where('key', 13)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76464', 'locality' => '', 'municipality_id' => Municipality::where('key', 13)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76465', 'locality' => '', 'municipality_id' => Municipality::where('key', 13)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76470', 'locality' => '', 'municipality_id' => Municipality::where('key', 13)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76471', 'locality' => '', 'municipality_id' => Municipality::where('key', 13)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76474', 'locality' => '', 'municipality_id' => Municipality::where('key', 13)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76476', 'locality' => '', 'municipality_id' => Municipality::where('key', 13)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76477', 'locality' => '', 'municipality_id' => Municipality::where('key', 13)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76478', 'locality' => '', 'municipality_id' => Municipality::where('key', 13)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76483', 'locality' => '', 'municipality_id' => Municipality::where('key', 13)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76484', 'locality' => '', 'municipality_id' => Municipality::where('key', 13)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76485', 'locality' => '', 'municipality_id' => Municipality::where('key', 13)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76486', 'locality' => '', 'municipality_id' => Municipality::where('key', 13)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76489', 'locality' => '', 'municipality_id' => Municipality::where('key', 13)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76490', 'locality' => '', 'municipality_id' => Municipality::where('key', 13)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76492', 'locality' => '', 'municipality_id' => Municipality::where('key', 13)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76493', 'locality' => '', 'municipality_id' => Municipality::where('key', 13)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76494', 'locality' => '', 'municipality_id' => Municipality::where('key', 13)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76495', 'locality' => '', 'municipality_id' => Municipality::where('key', 13)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76496', 'locality' => '', 'municipality_id' => Municipality::where('key', 13)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76499', 'locality' => '', 'municipality_id' => Municipality::where('key', 13)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76500', 'locality' => '', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76503', 'locality' => '', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76504', 'locality' => '', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76505', 'locality' => '', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76506', 'locality' => '', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76510', 'locality' => '', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76513', 'locality' => '', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76514', 'locality' => '', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76515', 'locality' => '', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76516', 'locality' => '', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76517', 'locality' => '', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76520', 'locality' => '', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76523', 'locality' => '', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76525', 'locality' => '', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76526', 'locality' => '', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76527', 'locality' => '', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76528', 'locality' => '', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76529', 'locality' => '', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76530', 'locality' => '', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76534', 'locality' => '', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76535', 'locality' => '', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76536', 'locality' => '', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76537', 'locality' => '', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76538', 'locality' => '', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76539', 'locality' => '', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76540', 'locality' => '', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76543', 'locality' => '', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76544', 'locality' => '', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76545', 'locality' => '', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76546', 'locality' => '', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76547', 'locality' => '', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76548', 'locality' => '', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76550', 'locality' => '', 'municipality_id' => Municipality::where('key', 15)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76553', 'locality' => '', 'municipality_id' => Municipality::where('key', 15)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76554', 'locality' => '', 'municipality_id' => Municipality::where('key', 15)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76555', 'locality' => '', 'municipality_id' => Municipality::where('key', 15)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76556', 'locality' => '', 'municipality_id' => Municipality::where('key', 15)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76557', 'locality' => '', 'municipality_id' => Municipality::where('key', 15)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76558', 'locality' => '', 'municipality_id' => Municipality::where('key', 15)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76560', 'locality' => '', 'municipality_id' => Municipality::where('key', 15)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76563', 'locality' => '', 'municipality_id' => Municipality::where('key', 15)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76564', 'locality' => '', 'municipality_id' => Municipality::where('key', 15)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76565', 'locality' => '', 'municipality_id' => Municipality::where('key', 15)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76566', 'locality' => '', 'municipality_id' => Municipality::where('key', 15)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76567', 'locality' => '', 'municipality_id' => Municipality::where('key', 15)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76568', 'locality' => '', 'municipality_id' => Municipality::where('key', 15)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76570', 'locality' => '', 'municipality_id' => Municipality::where('key', 15)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76573', 'locality' => '', 'municipality_id' => Municipality::where('key', 15)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76574', 'locality' => '', 'municipality_id' => Municipality::where('key', 15)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76575', 'locality' => '', 'municipality_id' => Municipality::where('key', 15)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76600', 'locality' => '', 'municipality_id' => Municipality::where('key', 18)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76605', 'locality' => '', 'municipality_id' => Municipality::where('key', 18)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76610', 'locality' => '', 'municipality_id' => Municipality::where('key', 18)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76613', 'locality' => '', 'municipality_id' => Municipality::where('key', 18)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76614', 'locality' => '', 'municipality_id' => Municipality::where('key', 18)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76615', 'locality' => '', 'municipality_id' => Municipality::where('key', 18)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76616', 'locality' => '', 'municipality_id' => Municipality::where('key', 18)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76617', 'locality' => '', 'municipality_id' => Municipality::where('key', 18)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76618', 'locality' => '', 'municipality_id' => Municipality::where('key', 18)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76620', 'locality' => '', 'municipality_id' => Municipality::where('key', 18)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76623', 'locality' => '', 'municipality_id' => Municipality::where('key', 18)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76624', 'locality' => '', 'municipality_id' => Municipality::where('key', 18)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76626', 'locality' => '', 'municipality_id' => Municipality::where('key', 18)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76627', 'locality' => '', 'municipality_id' => Municipality::where('key', 18)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76628', 'locality' => '', 'municipality_id' => Municipality::where('key', 18)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76630', 'locality' => '', 'municipality_id' => Municipality::where('key', 18)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76631', 'locality' => '', 'municipality_id' => Municipality::where('key', 18)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76632', 'locality' => '', 'municipality_id' => Municipality::where('key', 18)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76633', 'locality' => '', 'municipality_id' => Municipality::where('key', 18)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76634', 'locality' => '', 'municipality_id' => Municipality::where('key', 18)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76636', 'locality' => '', 'municipality_id' => Municipality::where('key', 18)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76637', 'locality' => '', 'municipality_id' => Municipality::where('key', 18)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76640', 'locality' => '', 'municipality_id' => Municipality::where('key', 18)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76643', 'locality' => '', 'municipality_id' => Municipality::where('key', 18)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76644', 'locality' => '', 'municipality_id' => Municipality::where('key', 18)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76646', 'locality' => '', 'municipality_id' => Municipality::where('key', 18)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76647', 'locality' => '', 'municipality_id' => Municipality::where('key', 18)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76649', 'locality' => '', 'municipality_id' => Municipality::where('key', 18)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76650', 'locality' => '', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76651', 'locality' => '', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76654', 'locality' => '', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76655', 'locality' => '', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76656', 'locality' => '', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76657', 'locality' => '', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76663', 'locality' => '', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76664', 'locality' => '', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76665', 'locality' => '', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76666', 'locality' => '', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76667', 'locality' => '', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76670', 'locality' => '', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76674', 'locality' => '', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76675', 'locality' => '', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76676', 'locality' => '', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76677', 'locality' => '', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76680', 'locality' => '', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76681', 'locality' => '', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76683', 'locality' => '', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76685', 'locality' => '', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76686', 'locality' => '', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76687', 'locality' => '', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76688', 'locality' => '', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76690', 'locality' => '', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76693', 'locality' => '', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76694', 'locality' => '', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76697', 'locality' => '', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76700', 'locality' => '', 'municipality_id' => Municipality::where('key', 12)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76703', 'locality' => '', 'municipality_id' => Municipality::where('key', 12)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76704', 'locality' => '', 'municipality_id' => Municipality::where('key', 12)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76705', 'locality' => '', 'municipality_id' => Municipality::where('key', 12)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76707', 'locality' => '', 'municipality_id' => Municipality::where('key', 12)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76708', 'locality' => '', 'municipality_id' => Municipality::where('key', 12)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76709', 'locality' => '', 'municipality_id' => Municipality::where('key', 12)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76710', 'locality' => '', 'municipality_id' => Municipality::where('key', 12)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76713', 'locality' => '', 'municipality_id' => Municipality::where('key', 12)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76714', 'locality' => '', 'municipality_id' => Municipality::where('key', 12)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76715', 'locality' => '', 'municipality_id' => Municipality::where('key', 12)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76720', 'locality' => '', 'municipality_id' => Municipality::where('key', 12)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76721', 'locality' => '', 'municipality_id' => Municipality::where('key', 12)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76722', 'locality' => '', 'municipality_id' => Municipality::where('key', 12)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76723', 'locality' => '', 'municipality_id' => Municipality::where('key', 12)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76724', 'locality' => '', 'municipality_id' => Municipality::where('key', 12)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76725', 'locality' => '', 'municipality_id' => Municipality::where('key', 12)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76726', 'locality' => '', 'municipality_id' => Municipality::where('key', 12)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76729', 'locality' => '', 'municipality_id' => Municipality::where('key', 12)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76740', 'locality' => '', 'municipality_id' => Municipality::where('key', 12)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76741', 'locality' => '', 'municipality_id' => Municipality::where('key', 12)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76743', 'locality' => '', 'municipality_id' => Municipality::where('key', 12)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76746', 'locality' => '', 'municipality_id' => Municipality::where('key', 12)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76750', 'locality' => '', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76753', 'locality' => '', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76754', 'locality' => '', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76755', 'locality' => '', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76756', 'locality' => '', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76757', 'locality' => '', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76773', 'locality' => '', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76774', 'locality' => '', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76775', 'locality' => '', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76776', 'locality' => '', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76780', 'locality' => '', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76781', 'locality' => '', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76783', 'locality' => '', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76785', 'locality' => '', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76786', 'locality' => '', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76790', 'locality' => '', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76791', 'locality' => '', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76794', 'locality' => '', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76795', 'locality' => '', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76796', 'locality' => '', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76799', 'locality' => '', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76800', 'locality' => 'San Juan del Rio', 'municipality_id' => Municipality::where('key', 16)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76803', 'locality' => 'San Juan del Rio', 'municipality_id' => Municipality::where('key', 16)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76804', 'locality' => 'San Juan del Rio', 'municipality_id' => Municipality::where('key', 16)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76805', 'locality' => 'San Juan del Rio', 'municipality_id' => Municipality::where('key', 16)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76806', 'locality' => 'San Juan del Rio', 'municipality_id' => Municipality::where('key', 16)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76807', 'locality' => 'San Juan del Rio', 'municipality_id' => Municipality::where('key', 16)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76810', 'locality' => '', 'municipality_id' => Municipality::where('key', 16)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76812', 'locality' => '', 'municipality_id' => Municipality::where('key', 16)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76813', 'locality' => '', 'municipality_id' => Municipality::where('key', 16)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76814', 'locality' => '', 'municipality_id' => Municipality::where('key', 16)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76815', 'locality' => '', 'municipality_id' => Municipality::where('key', 16)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76820', 'locality' => '', 'municipality_id' => Municipality::where('key', 16)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76821', 'locality' => '', 'municipality_id' => Municipality::where('key', 16)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76823', 'locality' => '', 'municipality_id' => Municipality::where('key', 16)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76824', 'locality' => '', 'municipality_id' => Municipality::where('key', 16)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76826', 'locality' => '', 'municipality_id' => Municipality::where('key', 16)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76827', 'locality' => '', 'municipality_id' => Municipality::where('key', 16)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76828', 'locality' => '', 'municipality_id' => Municipality::where('key', 16)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76829', 'locality' => '', 'municipality_id' => Municipality::where('key', 16)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76830', 'locality' => '', 'municipality_id' => Municipality::where('key', 16)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76833', 'locality' => '', 'municipality_id' => Municipality::where('key', 16)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76835', 'locality' => '', 'municipality_id' => Municipality::where('key', 16)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76837', 'locality' => '', 'municipality_id' => Municipality::where('key', 16)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76838', 'locality' => '', 'municipality_id' => Municipality::where('key', 16)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76840', 'locality' => '', 'municipality_id' => Municipality::where('key', 16)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76842', 'locality' => '', 'municipality_id' => Municipality::where('key', 16)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76843', 'locality' => '', 'municipality_id' => Municipality::where('key', 16)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76844', 'locality' => '', 'municipality_id' => Municipality::where('key', 16)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76845', 'locality' => '', 'municipality_id' => Municipality::where('key', 16)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76846', 'locality' => '', 'municipality_id' => Municipality::where('key', 16)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76847', 'locality' => '', 'municipality_id' => Municipality::where('key', 16)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76848', 'locality' => '', 'municipality_id' => Municipality::where('key', 16)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76849', 'locality' => '', 'municipality_id' => Municipality::where('key', 16)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76850', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76860', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76861', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76862', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76863', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76870', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76874', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76875', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76876', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76877', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76878', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76879', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76880', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76883', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76884', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76885', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76886', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76887', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76888', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76889', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76890', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76893', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76894', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76895', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76896', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76897', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76900', 'locality' => 'El Pueblito', 'municipality_id' => Municipality::where('key', 6)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76902', 'locality' => 'El Pueblito', 'municipality_id' => Municipality::where('key', 6)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76903', 'locality' => 'El Pueblito', 'municipality_id' => Municipality::where('key', 6)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76904', 'locality' => 'El Pueblito', 'municipality_id' => Municipality::where('key', 6)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76905', 'locality' => 'El Pueblito', 'municipality_id' => Municipality::where('key', 6)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76906', 'locality' => 'El Pueblito', 'municipality_id' => Municipality::where('key', 6)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76907', 'locality' => 'El Pueblito', 'municipality_id' => Municipality::where('key', 6)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76908', 'locality' => 'El Pueblito', 'municipality_id' => Municipality::where('key', 6)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76910', 'locality' => '', 'municipality_id' => Municipality::where('key', 6)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76912', 'locality' => '', 'municipality_id' => Municipality::where('key', 6)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76915', 'locality' => '', 'municipality_id' => Municipality::where('key', 6)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76920', 'locality' => '', 'municipality_id' => Municipality::where('key', 6)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76922', 'locality' => '', 'municipality_id' => Municipality::where('key', 6)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76923', 'locality' => '', 'municipality_id' => Municipality::where('key', 6)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76924', 'locality' => '', 'municipality_id' => Municipality::where('key', 6)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76925', 'locality' => '', 'municipality_id' => Municipality::where('key', 6)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76926', 'locality' => '', 'municipality_id' => Municipality::where('key', 6)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76927', 'locality' => '', 'municipality_id' => Municipality::where('key', 6)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76928', 'locality' => '', 'municipality_id' => Municipality::where('key', 6)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76930', 'locality' => '', 'municipality_id' => Municipality::where('key', 6)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76950', 'locality' => '', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76951', 'locality' => '', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76952', 'locality' => '', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76953', 'locality' => '', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76955', 'locality' => '', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76956', 'locality' => '', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76957', 'locality' => '', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76958', 'locality' => '', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76963', 'locality' => '', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76964', 'locality' => '', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76965', 'locality' => '', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76970', 'locality' => '', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76973', 'locality' => '', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76974', 'locality' => '', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76975', 'locality' => '', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76976', 'locality' => '', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76980', 'locality' => '', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76981', 'locality' => '', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76983', 'locality' => '', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76984', 'locality' => '', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76985', 'locality' => '', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76990', 'locality' => '', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76992', 'locality' => '', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76993', 'locality' => '', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76994', 'locality' => '', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76995', 'locality' => '', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76997', 'locality' => '', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 22)->first()->id , 'state_id' => 22],
            [ 'zip_code' => '76998', 'locality' => '', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 22)->first()->id , 'state_id' => 22],
        ];

        ZipCode::insert($zipCodes);
        unset($zipCodes);
    }
}
