<?php

namespace Database\Seeders;

use App\Models\ZipCode;
use App\Models\Municipality;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class QuintanaRooZipCodesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $zipCodes = [
            [ 'zip_code' => '77000', 'locality' => 'Chetumal', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77010', 'locality' => 'Chetumal', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77012', 'locality' => 'Chetumal', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77013', 'locality' => 'Chetumal', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77014', 'locality' => 'Chetumal', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77015', 'locality' => 'Chetumal', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77016', 'locality' => 'Chetumal', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77017', 'locality' => 'Chetumal', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77018', 'locality' => 'Chetumal', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77019', 'locality' => 'Chetumal', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77020', 'locality' => 'Chetumal', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77023', 'locality' => 'Chetumal', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77024', 'locality' => 'Chetumal', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77025', 'locality' => 'Chetumal', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77026', 'locality' => 'Chetumal', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77027', 'locality' => 'Chetumal', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77028', 'locality' => 'Chetumal', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77029', 'locality' => 'Chetumal', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77030', 'locality' => 'Chetumal', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77034', 'locality' => 'Chetumal', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77035', 'locality' => 'Chetumal', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77036', 'locality' => 'Chetumal', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77037', 'locality' => 'Chetumal', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77038', 'locality' => 'Chetumal', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77039', 'locality' => 'Chetumal', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77040', 'locality' => 'Chetumal', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77041', 'locality' => 'Chetumal', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77048', 'locality' => 'Chetumal', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77049', 'locality' => 'Chetumal', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77050', 'locality' => 'Chetumal', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77053', 'locality' => 'Chetumal', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77059', 'locality' => 'Chetumal', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77060', 'locality' => 'Chetumal', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77070', 'locality' => 'Chetumal', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77079', 'locality' => 'Chetumal', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77080', 'locality' => 'Chetumal', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77082', 'locality' => 'Chetumal', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77083', 'locality' => 'Chetumal', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77084', 'locality' => 'Chetumal', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77085', 'locality' => 'Chetumal', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77086', 'locality' => 'Chetumal', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77090', 'locality' => 'Chetumal', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77098', 'locality' => 'Chetumal', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77099', 'locality' => 'Chetumal', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77100', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77104', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77105', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77106', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77107', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77108', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77110', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77114', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77115', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77116', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77117', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77118', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77120', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77121', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77123', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77125', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77130', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77135', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77140', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77144', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77145', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77146', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77147', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77148', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77150', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77156', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77158', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77160', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77163', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77169', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77170', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77174', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77175', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77176', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77177', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77178', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77180', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77185', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77188', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77189', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77190', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77196', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77197', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77198', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77200', 'locality' => 'Felipe Carrillo Puerto', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77210', 'locality' => 'Felipe Carrillo Puerto', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77214', 'locality' => 'Felipe Carrillo Puerto', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77215', 'locality' => 'Felipe Carrillo Puerto', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77216', 'locality' => 'Felipe Carrillo Puerto', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77217', 'locality' => 'Felipe Carrillo Puerto', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77220', 'locality' => 'Felipe Carrillo Puerto', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77229', 'locality' => 'Felipe Carrillo Puerto', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77230', 'locality' => 'Felipe Carrillo Puerto', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77238', 'locality' => 'Felipe Carrillo Puerto', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77239', 'locality' => 'Felipe Carrillo Puerto', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77240', 'locality' => 'Felipe Carrillo Puerto', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77249', 'locality' => 'Felipe Carrillo Puerto', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77250', 'locality' => 'Felipe Carrillo Puerto', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77259', 'locality' => 'Felipe Carrillo Puerto', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77300', 'locality' => 'Kantunilkín', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77302', 'locality' => 'Kantunilkín', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77303', 'locality' => 'Kantunilkín', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77304', 'locality' => 'Kantunilkín', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77305', 'locality' => 'Kantunilkín', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77306', 'locality' => 'Kantunilkín', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77307', 'locality' => 'Kantunilkín', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77310', 'locality' => '', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77320', 'locality' => '', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77330', 'locality' => '', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77333', 'locality' => '', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77350', 'locality' => '', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77355', 'locality' => '', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77360', 'locality' => '', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77366', 'locality' => '', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77367', 'locality' => '', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77368', 'locality' => '', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77369', 'locality' => '', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77370', 'locality' => '', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77376', 'locality' => '', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77377', 'locality' => '', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77378', 'locality' => '', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77380', 'locality' => '', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77384', 'locality' => '', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77385', 'locality' => '', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77386', 'locality' => '', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77400', 'locality' => 'Isla Mujeres', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77402', 'locality' => 'Isla Mujeres', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77403', 'locality' => 'Isla Mujeres', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77404', 'locality' => 'Isla Mujeres', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77406', 'locality' => 'Isla Mujeres', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77407', 'locality' => 'Isla Mujeres', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77408', 'locality' => 'Isla Mujeres', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77409', 'locality' => 'Isla Mujeres', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77410', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77412', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77420', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77500', 'locality' => 'Cancún', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77503', 'locality' => 'Cancún', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77504', 'locality' => 'Cancún', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77505', 'locality' => 'Cancún', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77506', 'locality' => 'Cancún', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77507', 'locality' => 'Cancún', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77508', 'locality' => 'Cancún', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77509', 'locality' => 'Cancún', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77510', 'locality' => 'Cancún', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77513', 'locality' => 'Cancún', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77514', 'locality' => 'Cancún', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77515', 'locality' => 'Cancún', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77516', 'locality' => 'Cancún', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77517', 'locality' => 'Cancún', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77518', 'locality' => 'Cancún', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77519', 'locality' => 'Cancún', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77520', 'locality' => 'Cancún', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77524', 'locality' => 'Cancún', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77525', 'locality' => 'Cancún', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77526', 'locality' => 'Cancún', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77527', 'locality' => 'Cancún', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77528', 'locality' => 'Cancún', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77530', 'locality' => 'Cancún', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77533', 'locality' => 'Cancún', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77534', 'locality' => 'Cancún', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77535', 'locality' => 'Cancún', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77536', 'locality' => 'Cancún', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77537', 'locality' => 'Cancún', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77538', 'locality' => 'Cancún', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77539', 'locality' => 'Cancún', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77560', 'locality' => '', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77567', 'locality' => '', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77569', 'locality' => '', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77580', 'locality' => '', 'municipality_id' => Municipality::where('key', 11)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77586', 'locality' => '', 'municipality_id' => Municipality::where('key', 11)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77590', 'locality' => '', 'municipality_id' => Municipality::where('key', 11)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77600', 'locality' => 'Cozumel', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77609', 'locality' => 'Cozumel', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77610', 'locality' => 'Cozumel', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77613', 'locality' => 'Cozumel', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77620', 'locality' => 'Cozumel', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77622', 'locality' => 'Cozumel', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77645', 'locality' => 'Cozumel', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77660', 'locality' => 'Cozumel', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77664', 'locality' => 'Cozumel', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77665', 'locality' => 'Cozumel', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77666', 'locality' => 'Cozumel', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77667', 'locality' => 'Cozumel', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77670', 'locality' => 'Cozumel', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77673', 'locality' => 'Cozumel', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77675', 'locality' => 'Cozumel', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77676', 'locality' => 'Cozumel', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77689', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77710', 'locality' => 'Playa del Carmen', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77712', 'locality' => 'Playa del Carmen', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77713', 'locality' => 'Playa del Carmen', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77714', 'locality' => 'Playa del Carmen', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77716', 'locality' => 'Playa del Carmen', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77717', 'locality' => 'Playa del Carmen', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77718', 'locality' => 'Playa del Carmen', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77720', 'locality' => 'Playa del Carmen', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77723', 'locality' => 'Playa del Carmen', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77724', 'locality' => 'Playa del Carmen', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77725', 'locality' => 'Playa del Carmen', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77726', 'locality' => 'Playa del Carmen', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77727', 'locality' => 'Playa del Carmen', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77728', 'locality' => 'Playa del Carmen', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77730', 'locality' => '', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77733', 'locality' => '', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77734', 'locality' => '', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77735', 'locality' => '', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77740', 'locality' => '', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77760', 'locality' => '', 'municipality_id' => Municipality::where('key', 9)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77762', 'locality' => '', 'municipality_id' => Municipality::where('key', 9)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77763', 'locality' => '', 'municipality_id' => Municipality::where('key', 9)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77764', 'locality' => '', 'municipality_id' => Municipality::where('key', 9)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77766', 'locality' => '', 'municipality_id' => Municipality::where('key', 9)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77768', 'locality' => '', 'municipality_id' => Municipality::where('key', 9)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77772', 'locality' => '', 'municipality_id' => Municipality::where('key', 9)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77774', 'locality' => '', 'municipality_id' => Municipality::where('key', 9)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77776', 'locality' => '', 'municipality_id' => Municipality::where('key', 9)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77785', 'locality' => '', 'municipality_id' => Municipality::where('key', 9)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77786', 'locality' => '', 'municipality_id' => Municipality::where('key', 9)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77793', 'locality' => '', 'municipality_id' => Municipality::where('key', 9)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77794', 'locality' => '', 'municipality_id' => Municipality::where('key', 9)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77795', 'locality' => '', 'municipality_id' => Municipality::where('key', 9)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77796', 'locality' => '', 'municipality_id' => Municipality::where('key', 9)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77800', 'locality' => '', 'municipality_id' => Municipality::where('key', 6)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77805', 'locality' => '', 'municipality_id' => Municipality::where('key', 6)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77806', 'locality' => '', 'municipality_id' => Municipality::where('key', 6)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77807', 'locality' => '', 'municipality_id' => Municipality::where('key', 6)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77808', 'locality' => '', 'municipality_id' => Municipality::where('key', 6)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77809', 'locality' => '', 'municipality_id' => Municipality::where('key', 6)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77850', 'locality' => '', 'municipality_id' => Municipality::where('key', 6)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77858', 'locality' => '', 'municipality_id' => Municipality::where('key', 6)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77859', 'locality' => '', 'municipality_id' => Municipality::where('key', 6)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77870', 'locality' => '', 'municipality_id' => Municipality::where('key', 6)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77874', 'locality' => '', 'municipality_id' => Municipality::where('key', 6)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77875', 'locality' => '', 'municipality_id' => Municipality::where('key', 6)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77876', 'locality' => '', 'municipality_id' => Municipality::where('key', 6)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77878', 'locality' => '', 'municipality_id' => Municipality::where('key', 6)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77880', 'locality' => '', 'municipality_id' => Municipality::where('key', 6)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77882', 'locality' => '', 'municipality_id' => Municipality::where('key', 6)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77883', 'locality' => '', 'municipality_id' => Municipality::where('key', 6)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77889', 'locality' => '', 'municipality_id' => Municipality::where('key', 6)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77890', 'locality' => '', 'municipality_id' => Municipality::where('key', 6)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77893', 'locality' => '', 'municipality_id' => Municipality::where('key', 6)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77894', 'locality' => '', 'municipality_id' => Municipality::where('key', 6)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77895', 'locality' => '', 'municipality_id' => Municipality::where('key', 6)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77896', 'locality' => '', 'municipality_id' => Municipality::where('key', 6)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77898', 'locality' => '', 'municipality_id' => Municipality::where('key', 6)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77899', 'locality' => '', 'municipality_id' => Municipality::where('key', 6)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77900', 'locality' => '', 'municipality_id' => Municipality::where('key', 10)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77904', 'locality' => '', 'municipality_id' => Municipality::where('key', 10)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77905', 'locality' => '', 'municipality_id' => Municipality::where('key', 10)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77906', 'locality' => '', 'municipality_id' => Municipality::where('key', 10)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77907', 'locality' => '', 'municipality_id' => Municipality::where('key', 10)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77910', 'locality' => '', 'municipality_id' => Municipality::where('key', 10)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77913', 'locality' => '', 'municipality_id' => Municipality::where('key', 10)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77914', 'locality' => '', 'municipality_id' => Municipality::where('key', 10)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77915', 'locality' => '', 'municipality_id' => Municipality::where('key', 10)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77916', 'locality' => '', 'municipality_id' => Municipality::where('key', 10)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77917', 'locality' => '', 'municipality_id' => Municipality::where('key', 10)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77920', 'locality' => '', 'municipality_id' => Municipality::where('key', 10)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77923', 'locality' => '', 'municipality_id' => Municipality::where('key', 10)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77924', 'locality' => '', 'municipality_id' => Municipality::where('key', 10)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77925', 'locality' => '', 'municipality_id' => Municipality::where('key', 10)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77926', 'locality' => '', 'municipality_id' => Municipality::where('key', 10)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77927', 'locality' => '', 'municipality_id' => Municipality::where('key', 10)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77930', 'locality' => 'Bacalar', 'municipality_id' => Municipality::where('key', 10)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77933', 'locality' => 'Bacalar', 'municipality_id' => Municipality::where('key', 10)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77934', 'locality' => 'Bacalar', 'municipality_id' => Municipality::where('key', 10)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77935', 'locality' => 'Bacalar', 'municipality_id' => Municipality::where('key', 10)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77936', 'locality' => '', 'municipality_id' => Municipality::where('key', 10)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77937', 'locality' => '', 'municipality_id' => Municipality::where('key', 10)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77940', 'locality' => '', 'municipality_id' => Municipality::where('key', 10)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77943', 'locality' => '', 'municipality_id' => Municipality::where('key', 10)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77944', 'locality' => '', 'municipality_id' => Municipality::where('key', 10)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77945', 'locality' => '', 'municipality_id' => Municipality::where('key', 10)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77946', 'locality' => '', 'municipality_id' => Municipality::where('key', 10)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77947', 'locality' => '', 'municipality_id' => Municipality::where('key', 10)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77950', 'locality' => '', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77953', 'locality' => '', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77954', 'locality' => '', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77955', 'locality' => '', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77957', 'locality' => '', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77959', 'locality' => '', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77960', 'locality' => '', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77962', 'locality' => '', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77963', 'locality' => '', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77965', 'locality' => '', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77966', 'locality' => '', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77970', 'locality' => '', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77976', 'locality' => '', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77977', 'locality' => '', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77980', 'locality' => '', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77983', 'locality' => '', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77984', 'locality' => '', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77985', 'locality' => '', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77986', 'locality' => '', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77987', 'locality' => '', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77990', 'locality' => '', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77992', 'locality' => '', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77994', 'locality' => '', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77995', 'locality' => '', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 23)->first()->id , 'state_id' => 23],
            [ 'zip_code' => '77997', 'locality' => '', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 23)->first()->id , 'state_id' => 23],
        ];

        ZipCode::insert($zipCodes);
        unset($zipCodes);
    }
}
