<?php

namespace Database\Seeders;

use App\Models\ZipCode;
use App\Models\Municipality;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class TlaxlacaZipCodesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $zipCodes = [
            [ 'zip_code' => '90000', 'locality' => 'Tlaxcala de Xicohténcatl', 'municipality_id' => Municipality::where('key', 33)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90005', 'locality' => 'Tlaxcala de Xicohténcatl', 'municipality_id' => Municipality::where('key', 33)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90006', 'locality' => 'Tlaxcala de Xicohténcatl', 'municipality_id' => Municipality::where('key', 33)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90010', 'locality' => 'Tlaxcala de Xicohténcatl', 'municipality_id' => Municipality::where('key', 33)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90013', 'locality' => 'Tlaxcala de Xicohténcatl', 'municipality_id' => Municipality::where('key', 33)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90014', 'locality' => 'Tlaxcala de Xicohténcatl', 'municipality_id' => Municipality::where('key', 33)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90019', 'locality' => 'Tlaxcala de Xicohténcatl', 'municipality_id' => Municipality::where('key', 33)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90020', 'locality' => 'Tlaxcala de Xicohténcatl', 'municipality_id' => Municipality::where('key', 33)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90030', 'locality' => 'Tlaxcala de Xicohténcatl', 'municipality_id' => Municipality::where('key', 33)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90040', 'locality' => 'Tlaxcala de Xicohténcatl', 'municipality_id' => Municipality::where('key', 33)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90050', 'locality' => 'Tlaxcala de Xicohténcatl', 'municipality_id' => Municipality::where('key', 33)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90060', 'locality' => 'Tlaxcala de Xicohténcatl', 'municipality_id' => Municipality::where('key', 33)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90062', 'locality' => 'Tlaxcala de Xicohténcatl', 'municipality_id' => Municipality::where('key', 33)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90080', 'locality' => 'Tlaxcala de Xicohténcatl', 'municipality_id' => Municipality::where('key', 33)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90090', 'locality' => 'Tlaxcala de Xicohténcatl', 'municipality_id' => Municipality::where('key', 33)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90099', 'locality' => 'Tlaxcala de Xicohténcatl', 'municipality_id' => Municipality::where('key', 33)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90100', 'locality' => '', 'municipality_id' => Municipality::where('key', 33)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90102', 'locality' => '', 'municipality_id' => Municipality::where('key', 33)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90105', 'locality' => '', 'municipality_id' => Municipality::where('key', 33)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90110', 'locality' => '', 'municipality_id' => Municipality::where('key', 33)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90111', 'locality' => '', 'municipality_id' => Municipality::where('key', 33)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90112', 'locality' => '', 'municipality_id' => Municipality::where('key', 33)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90114', 'locality' => '', 'municipality_id' => Municipality::where('key', 33)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90115', 'locality' => '', 'municipality_id' => Municipality::where('key', 33)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90117', 'locality' => '', 'municipality_id' => Municipality::where('key', 33)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90118', 'locality' => '', 'municipality_id' => Municipality::where('key', 33)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90120', 'locality' => '', 'municipality_id' => Municipality::where('key', 15)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90121', 'locality' => '', 'municipality_id' => Municipality::where('key', 15)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90122', 'locality' => '', 'municipality_id' => Municipality::where('key', 15)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90123', 'locality' => '', 'municipality_id' => Municipality::where('key', 15)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90124', 'locality' => '', 'municipality_id' => Municipality::where('key', 15)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90125', 'locality' => '', 'municipality_id' => Municipality::where('key', 15)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90126', 'locality' => '', 'municipality_id' => Municipality::where('key', 15)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90127', 'locality' => '', 'municipality_id' => Municipality::where('key', 15)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90128', 'locality' => '', 'municipality_id' => Municipality::where('key', 15)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90130', 'locality' => '', 'municipality_id' => Municipality::where('key', 15)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90131', 'locality' => '', 'municipality_id' => Municipality::where('key', 15)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90132', 'locality' => '', 'municipality_id' => Municipality::where('key', 15)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90133', 'locality' => '', 'municipality_id' => Municipality::where('key', 15)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90134', 'locality' => '', 'municipality_id' => Municipality::where('key', 15)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90135', 'locality' => '', 'municipality_id' => Municipality::where('key', 56)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90137', 'locality' => '', 'municipality_id' => Municipality::where('key', 56)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90138', 'locality' => '', 'municipality_id' => Municipality::where('key', 56)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90139', 'locality' => '', 'municipality_id' => Municipality::where('key', 56)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90140', 'locality' => '', 'municipality_id' => Municipality::where('key', 24)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90145', 'locality' => '', 'municipality_id' => Municipality::where('key', 24)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90147', 'locality' => '', 'municipality_id' => Municipality::where('key', 24)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90150', 'locality' => '', 'municipality_id' => Municipality::where('key', 24)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90151', 'locality' => '', 'municipality_id' => Municipality::where('key', 24)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90152', 'locality' => '', 'municipality_id' => Municipality::where('key', 24)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90155', 'locality' => '', 'municipality_id' => Municipality::where('key', 24)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90156', 'locality' => '', 'municipality_id' => Municipality::where('key', 24)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90160', 'locality' => '', 'municipality_id' => Municipality::where('key', 36)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90163', 'locality' => '', 'municipality_id' => Municipality::where('key', 36)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90164', 'locality' => '', 'municipality_id' => Municipality::where('key', 36)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90165', 'locality' => '', 'municipality_id' => Municipality::where('key', 36)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90166', 'locality' => '', 'municipality_id' => Municipality::where('key', 36)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90168', 'locality' => '', 'municipality_id' => Municipality::where('key', 36)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90170', 'locality' => '', 'municipality_id' => Municipality::where('key', 36)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90180', 'locality' => '', 'municipality_id' => Municipality::where('key', 29)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90182', 'locality' => '', 'municipality_id' => Municipality::where('key', 29)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90183', 'locality' => '', 'municipality_id' => Municipality::where('key', 29)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90193', 'locality' => '', 'municipality_id' => Municipality::where('key', 60)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90194', 'locality' => '', 'municipality_id' => Municipality::where('key', 60)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90195', 'locality' => '', 'municipality_id' => Municipality::where('key', 53)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90200', 'locality' => 'Calpulalpan', 'municipality_id' => Municipality::where('key', 6)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90202', 'locality' => 'Calpulalpan', 'municipality_id' => Municipality::where('key', 6)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90203', 'locality' => 'Calpulalpan', 'municipality_id' => Municipality::where('key', 6)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90204', 'locality' => 'Calpulalpan', 'municipality_id' => Municipality::where('key', 6)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90205', 'locality' => 'Calpulalpan', 'municipality_id' => Municipality::where('key', 6)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90207', 'locality' => 'Calpulalpan', 'municipality_id' => Municipality::where('key', 6)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90208', 'locality' => 'Calpulalpan', 'municipality_id' => Municipality::where('key', 6)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90210', 'locality' => '', 'municipality_id' => Municipality::where('key', 6)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90213', 'locality' => '', 'municipality_id' => Municipality::where('key', 6)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90214', 'locality' => '', 'municipality_id' => Municipality::where('key', 6)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90218', 'locality' => '', 'municipality_id' => Municipality::where('key', 6)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90220', 'locality' => '', 'municipality_id' => Municipality::where('key', 6)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90222', 'locality' => '', 'municipality_id' => Municipality::where('key', 6)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90224', 'locality' => '', 'municipality_id' => Municipality::where('key', 6)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90225', 'locality' => '', 'municipality_id' => Municipality::where('key', 6)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90226', 'locality' => '', 'municipality_id' => Municipality::where('key', 6)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90230', 'locality' => '', 'municipality_id' => Municipality::where('key', 20)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90231', 'locality' => '', 'municipality_id' => Municipality::where('key', 20)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90233', 'locality' => '', 'municipality_id' => Municipality::where('key', 20)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90234', 'locality' => '', 'municipality_id' => Municipality::where('key', 20)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90235', 'locality' => '', 'municipality_id' => Municipality::where('key', 45)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90240', 'locality' => '', 'municipality_id' => Municipality::where('key', 14)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90241', 'locality' => '', 'municipality_id' => Municipality::where('key', 14)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90243', 'locality' => '', 'municipality_id' => Municipality::where('key', 14)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90244', 'locality' => '', 'municipality_id' => Municipality::where('key', 14)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90245', 'locality' => '', 'municipality_id' => Municipality::where('key', 14)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90246', 'locality' => '', 'municipality_id' => Municipality::where('key', 14)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90247', 'locality' => '', 'municipality_id' => Municipality::where('key', 14)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90250', 'locality' => '', 'municipality_id' => Municipality::where('key', 34)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90251', 'locality' => '', 'municipality_id' => Municipality::where('key', 34)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90253', 'locality' => '', 'municipality_id' => Municipality::where('key', 34)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90255', 'locality' => '', 'municipality_id' => Municipality::where('key', 34)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90256', 'locality' => '', 'municipality_id' => Municipality::where('key', 34)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90257', 'locality' => '', 'municipality_id' => Municipality::where('key', 34)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90258', 'locality' => '', 'municipality_id' => Municipality::where('key', 34)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90259', 'locality' => '', 'municipality_id' => Municipality::where('key', 34)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90260', 'locality' => '', 'municipality_id' => Municipality::where('key', 34)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90261', 'locality' => '', 'municipality_id' => Municipality::where('key', 34)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90262', 'locality' => '', 'municipality_id' => Municipality::where('key', 34)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90263', 'locality' => '', 'municipality_id' => Municipality::where('key', 34)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90264', 'locality' => '', 'municipality_id' => Municipality::where('key', 34)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90265', 'locality' => '', 'municipality_id' => Municipality::where('key', 34)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90266', 'locality' => '', 'municipality_id' => Municipality::where('key', 34)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90267', 'locality' => '', 'municipality_id' => Municipality::where('key', 34)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90270', 'locality' => '', 'municipality_id' => Municipality::where('key', 34)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90271', 'locality' => '', 'municipality_id' => Municipality::where('key', 34)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90273', 'locality' => '', 'municipality_id' => Municipality::where('key', 34)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90274', 'locality' => '', 'municipality_id' => Municipality::where('key', 34)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90275', 'locality' => '', 'municipality_id' => Municipality::where('key', 34)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90276', 'locality' => '', 'municipality_id' => Municipality::where('key', 34)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90277', 'locality' => '', 'municipality_id' => Municipality::where('key', 34)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90278', 'locality' => '', 'municipality_id' => Municipality::where('key', 34)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90280', 'locality' => '', 'municipality_id' => Municipality::where('key', 21)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90283', 'locality' => '', 'municipality_id' => Municipality::where('key', 21)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90284', 'locality' => '', 'municipality_id' => Municipality::where('key', 21)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90285', 'locality' => '', 'municipality_id' => Municipality::where('key', 21)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90286', 'locality' => '', 'municipality_id' => Municipality::where('key', 21)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90287', 'locality' => '', 'municipality_id' => Municipality::where('key', 21)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90288', 'locality' => '', 'municipality_id' => Municipality::where('key', 21)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90290', 'locality' => '', 'municipality_id' => Municipality::where('key', 12)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90291', 'locality' => '', 'municipality_id' => Municipality::where('key', 12)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90292', 'locality' => '', 'municipality_id' => Municipality::where('key', 12)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90293', 'locality' => '', 'municipality_id' => Municipality::where('key', 12)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90294', 'locality' => '', 'municipality_id' => Municipality::where('key', 12)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90295', 'locality' => '', 'municipality_id' => Municipality::where('key', 12)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90297', 'locality' => '', 'municipality_id' => Municipality::where('key', 12)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90298', 'locality' => '', 'municipality_id' => Municipality::where('key', 12)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90300', 'locality' => 'Apizaco', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90319', 'locality' => 'Apizaco', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90320', 'locality' => 'Apizaco', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90323', 'locality' => 'Apizaco', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90329', 'locality' => 'Apizaco', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90330', 'locality' => 'Apizaco', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90337', 'locality' => 'Apizaco', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90338', 'locality' => 'Apizaco', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90339', 'locality' => 'Apizaco', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90340', 'locality' => 'Apizaco', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90341', 'locality' => 'Apizaco', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90342', 'locality' => 'Apizaco', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90347', 'locality' => 'Apizaco', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90350', 'locality' => 'Apizaco', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90355', 'locality' => 'Apizaco', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90356', 'locality' => 'Apizaco', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90357', 'locality' => 'Apizaco', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90358', 'locality' => 'Apizaco', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90360', 'locality' => 'Apizaco', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90370', 'locality' => 'Apizaco', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90378', 'locality' => 'Apizaco', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90380', 'locality' => 'Apizaco', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90401', 'locality' => '', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90402', 'locality' => '', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90403', 'locality' => '', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90404', 'locality' => '', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90405', 'locality' => '', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90406', 'locality' => '', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90407', 'locality' => '', 'municipality_id' => Municipality::where('key', 5)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90410', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90411', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90413', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90414', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90415', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90416', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90418', 'locality' => '', 'municipality_id' => Municipality::where('key', 3)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90420', 'locality' => '', 'municipality_id' => Municipality::where('key', 11)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90421', 'locality' => '', 'municipality_id' => Municipality::where('key', 11)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90423', 'locality' => '', 'municipality_id' => Municipality::where('key', 11)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90425', 'locality' => '', 'municipality_id' => Municipality::where('key', 11)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90426', 'locality' => '', 'municipality_id' => Municipality::where('key', 11)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90427', 'locality' => '', 'municipality_id' => Municipality::where('key', 11)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90428', 'locality' => '', 'municipality_id' => Municipality::where('key', 11)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90430', 'locality' => '', 'municipality_id' => Municipality::where('key', 31)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90432', 'locality' => '', 'municipality_id' => Municipality::where('key', 31)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90433', 'locality' => '', 'municipality_id' => Municipality::where('key', 31)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90434', 'locality' => '', 'municipality_id' => Municipality::where('key', 31)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90435', 'locality' => '', 'municipality_id' => Municipality::where('key', 31)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90436', 'locality' => '', 'municipality_id' => Municipality::where('key', 31)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90437', 'locality' => '', 'municipality_id' => Municipality::where('key', 31)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90438', 'locality' => '', 'municipality_id' => Municipality::where('key', 31)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90440', 'locality' => '', 'municipality_id' => Municipality::where('key', 40)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90443', 'locality' => '', 'municipality_id' => Municipality::where('key', 40)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90444', 'locality' => '', 'municipality_id' => Municipality::where('key', 40)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90445', 'locality' => '', 'municipality_id' => Municipality::where('key', 55)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90446', 'locality' => '', 'municipality_id' => Municipality::where('key', 55)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90447', 'locality' => '', 'municipality_id' => Municipality::where('key', 55)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90448', 'locality' => '', 'municipality_id' => Municipality::where('key', 55)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90450', 'locality' => '', 'municipality_id' => Municipality::where('key', 43)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90453', 'locality' => '', 'municipality_id' => Municipality::where('key', 43)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90454', 'locality' => '', 'municipality_id' => Municipality::where('key', 43)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90455', 'locality' => '', 'municipality_id' => Municipality::where('key', 43)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90456', 'locality' => '', 'municipality_id' => Municipality::where('key', 43)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90457', 'locality' => '', 'municipality_id' => Municipality::where('key', 43)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90458', 'locality' => '', 'municipality_id' => Municipality::where('key', 43)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90459', 'locality' => '', 'municipality_id' => Municipality::where('key', 43)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90460', 'locality' => '', 'municipality_id' => Municipality::where('key', 39)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90463', 'locality' => '', 'municipality_id' => Municipality::where('key', 39)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90465', 'locality' => '', 'municipality_id' => Municipality::where('key', 39)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90470', 'locality' => '', 'municipality_id' => Municipality::where('key', 39)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90480', 'locality' => '', 'municipality_id' => Municipality::where('key', 35)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90482', 'locality' => '', 'municipality_id' => Municipality::where('key', 35)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90484', 'locality' => '', 'municipality_id' => Municipality::where('key', 35)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90490', 'locality' => '', 'municipality_id' => Municipality::where('key', 38)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90491', 'locality' => '', 'municipality_id' => Municipality::where('key', 38)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90493', 'locality' => '', 'municipality_id' => Municipality::where('key', 38)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90494', 'locality' => '', 'municipality_id' => Municipality::where('key', 38)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90495', 'locality' => '', 'municipality_id' => Municipality::where('key', 52)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90496', 'locality' => '', 'municipality_id' => Municipality::where('key', 52)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90497', 'locality' => '', 'municipality_id' => Municipality::where('key', 52)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90498', 'locality' => '', 'municipality_id' => Municipality::where('key', 52)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90500', 'locality' => 'Huamantla', 'municipality_id' => Municipality::where('key', 13)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90502', 'locality' => 'Huamantla', 'municipality_id' => Municipality::where('key', 13)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90503', 'locality' => 'Huamantla', 'municipality_id' => Municipality::where('key', 13)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90505', 'locality' => 'Huamantla', 'municipality_id' => Municipality::where('key', 13)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90506', 'locality' => 'Huamantla', 'municipality_id' => Municipality::where('key', 13)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90507', 'locality' => 'Huamantla', 'municipality_id' => Municipality::where('key', 13)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90508', 'locality' => 'Huamantla', 'municipality_id' => Municipality::where('key', 13)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90509', 'locality' => 'Huamantla', 'municipality_id' => Municipality::where('key', 13)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90510', 'locality' => '', 'municipality_id' => Municipality::where('key', 13)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90513', 'locality' => '', 'municipality_id' => Municipality::where('key', 13)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90514', 'locality' => '', 'municipality_id' => Municipality::where('key', 13)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90515', 'locality' => '', 'municipality_id' => Municipality::where('key', 13)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90520', 'locality' => '', 'municipality_id' => Municipality::where('key', 13)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90525', 'locality' => '', 'municipality_id' => Municipality::where('key', 13)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90526', 'locality' => '', 'municipality_id' => Municipality::where('key', 13)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90527', 'locality' => '', 'municipality_id' => Municipality::where('key', 13)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90530', 'locality' => '', 'municipality_id' => Municipality::where('key', 13)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90534', 'locality' => '', 'municipality_id' => Municipality::where('key', 13)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90535', 'locality' => '', 'municipality_id' => Municipality::where('key', 13)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90540', 'locality' => '', 'municipality_id' => Municipality::where('key', 30)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90542', 'locality' => '', 'municipality_id' => Municipality::where('key', 30)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90543', 'locality' => '', 'municipality_id' => Municipality::where('key', 30)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90544', 'locality' => '', 'municipality_id' => Municipality::where('key', 30)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90545', 'locality' => '', 'municipality_id' => Municipality::where('key', 47)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90546', 'locality' => '', 'municipality_id' => Municipality::where('key', 47)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90547', 'locality' => '', 'municipality_id' => Municipality::where('key', 46)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90548', 'locality' => '', 'municipality_id' => Municipality::where('key', 46)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90550', 'locality' => '', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90553', 'locality' => '', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90554', 'locality' => '', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90555', 'locality' => '', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90556', 'locality' => '', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90557', 'locality' => '', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90558', 'locality' => '', 'municipality_id' => Municipality::where('key', 4)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90560', 'locality' => '', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90562', 'locality' => '', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90563', 'locality' => '', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90564', 'locality' => '', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90565', 'locality' => '', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90567', 'locality' => '', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90568', 'locality' => '', 'municipality_id' => Municipality::where('key', 8)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90570', 'locality' => '', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90573', 'locality' => '', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90575', 'locality' => '', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90576', 'locality' => '', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90577', 'locality' => '', 'municipality_id' => Municipality::where('key', 7)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90580', 'locality' => '', 'municipality_id' => Municipality::where('key', 16)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90583', 'locality' => '', 'municipality_id' => Municipality::where('key', 16)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90584', 'locality' => '', 'municipality_id' => Municipality::where('key', 16)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90585', 'locality' => '', 'municipality_id' => Municipality::where('key', 16)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90586', 'locality' => '', 'municipality_id' => Municipality::where('key', 16)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90590', 'locality' => '', 'municipality_id' => Municipality::where('key', 37)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90592', 'locality' => '', 'municipality_id' => Municipality::where('key', 37)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90594', 'locality' => '', 'municipality_id' => Municipality::where('key', 37)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90595', 'locality' => '', 'municipality_id' => Municipality::where('key', 37)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90596', 'locality' => '', 'municipality_id' => Municipality::where('key', 37)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90600', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90605', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90606', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90608', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90610', 'locality' => '', 'municipality_id' => Municipality::where('key', 2)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90620', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90623', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90624', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90630', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90635', 'locality' => '', 'municipality_id' => Municipality::where('key', 1)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90640', 'locality' => '', 'municipality_id' => Municipality::where('key', 26)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90643', 'locality' => '', 'municipality_id' => Municipality::where('key', 26)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90644', 'locality' => '', 'municipality_id' => Municipality::where('key', 26)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90645', 'locality' => '', 'municipality_id' => Municipality::where('key', 26)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90646', 'locality' => '', 'municipality_id' => Municipality::where('key', 26)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90650', 'locality' => '', 'municipality_id' => Municipality::where('key', 26)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90653', 'locality' => '', 'municipality_id' => Municipality::where('key', 26)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90660', 'locality' => '', 'municipality_id' => Municipality::where('key', 9)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90670', 'locality' => '', 'municipality_id' => Municipality::where('key', 18)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90676', 'locality' => '', 'municipality_id' => Municipality::where('key', 18)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90680', 'locality' => '', 'municipality_id' => Municipality::where('key', 18)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90690', 'locality' => '', 'municipality_id' => Municipality::where('key', 18)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90692', 'locality' => '', 'municipality_id' => Municipality::where('key', 18)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90693', 'locality' => '', 'municipality_id' => Municipality::where('key', 18)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90700', 'locality' => '', 'municipality_id' => Municipality::where('key', 19)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90710', 'locality' => '', 'municipality_id' => Municipality::where('key', 23)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90712', 'locality' => '', 'municipality_id' => Municipality::where('key', 23)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90713', 'locality' => '', 'municipality_id' => Municipality::where('key', 23)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90715', 'locality' => '', 'municipality_id' => Municipality::where('key', 23)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90716', 'locality' => '', 'municipality_id' => Municipality::where('key', 23)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90717', 'locality' => '', 'municipality_id' => Municipality::where('key', 23)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90718', 'locality' => '', 'municipality_id' => Municipality::where('key', 23)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90721', 'locality' => '', 'municipality_id' => Municipality::where('key', 23)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90722', 'locality' => '', 'municipality_id' => Municipality::where('key', 23)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90723', 'locality' => '', 'municipality_id' => Municipality::where('key', 23)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90725', 'locality' => '', 'municipality_id' => Municipality::where('key', 57)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90730', 'locality' => '', 'municipality_id' => Municipality::where('key', 32)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90733', 'locality' => '', 'municipality_id' => Municipality::where('key', 32)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90734', 'locality' => '', 'municipality_id' => Municipality::where('key', 32)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90735', 'locality' => '', 'municipality_id' => Municipality::where('key', 49)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90736', 'locality' => '', 'municipality_id' => Municipality::where('key', 49)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90737', 'locality' => '', 'municipality_id' => Municipality::where('key', 49)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90738', 'locality' => '', 'municipality_id' => Municipality::where('key', 51)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90740', 'locality' => '', 'municipality_id' => Municipality::where('key', 44)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90750', 'locality' => '', 'municipality_id' => Municipality::where('key', 44)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90754', 'locality' => '', 'municipality_id' => Municipality::where('key', 44)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90760', 'locality' => '', 'municipality_id' => Municipality::where('key', 54)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90770', 'locality' => '', 'municipality_id' => Municipality::where('key', 58)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90773', 'locality' => '', 'municipality_id' => Municipality::where('key', 58)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90774', 'locality' => '', 'municipality_id' => Municipality::where('key', 58)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90775', 'locality' => '', 'municipality_id' => Municipality::where('key', 58)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90780', 'locality' => '', 'municipality_id' => Municipality::where('key', 42)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90790', 'locality' => '', 'municipality_id' => Municipality::where('key', 41)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90791', 'locality' => '', 'municipality_id' => Municipality::where('key', 41)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90796', 'locality' => '', 'municipality_id' => Municipality::where('key', 41)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90800', 'locality' => 'Chiautempan', 'municipality_id' => Municipality::where('key', 10)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90802', 'locality' => 'Chiautempan', 'municipality_id' => Municipality::where('key', 10)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90803', 'locality' => 'Chiautempan', 'municipality_id' => Municipality::where('key', 10)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90804', 'locality' => 'Chiautempan', 'municipality_id' => Municipality::where('key', 10)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90805', 'locality' => 'Chiautempan', 'municipality_id' => Municipality::where('key', 10)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90806', 'locality' => 'Chiautempan', 'municipality_id' => Municipality::where('key', 10)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90807', 'locality' => 'Chiautempan', 'municipality_id' => Municipality::where('key', 10)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90810', 'locality' => '', 'municipality_id' => Municipality::where('key', 10)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90820', 'locality' => '', 'municipality_id' => Municipality::where('key', 10)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90821', 'locality' => '', 'municipality_id' => Municipality::where('key', 10)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90830', 'locality' => '', 'municipality_id' => Municipality::where('key', 48)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90833', 'locality' => '', 'municipality_id' => Municipality::where('key', 48)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90834', 'locality' => '', 'municipality_id' => Municipality::where('key', 48)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90835', 'locality' => '', 'municipality_id' => Municipality::where('key', 48)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90843', 'locality' => '', 'municipality_id' => Municipality::where('key', 50)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90845', 'locality' => '', 'municipality_id' => Municipality::where('key', 50)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90847', 'locality' => '', 'municipality_id' => Municipality::where('key', 50)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90850', 'locality' => '', 'municipality_id' => Municipality::where('key', 28)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90855', 'locality' => '', 'municipality_id' => Municipality::where('key', 28)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90860', 'locality' => '', 'municipality_id' => Municipality::where('key', 22)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90861', 'locality' => '', 'municipality_id' => Municipality::where('key', 22)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90864', 'locality' => '', 'municipality_id' => Municipality::where('key', 22)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90867', 'locality' => '', 'municipality_id' => Municipality::where('key', 59)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90870', 'locality' => '', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90873', 'locality' => '', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90874', 'locality' => '', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90875', 'locality' => '', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90876', 'locality' => '', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90877', 'locality' => '', 'municipality_id' => Municipality::where('key', 17)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90880', 'locality' => '', 'municipality_id' => Municipality::where('key', 27)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90883', 'locality' => '', 'municipality_id' => Municipality::where('key', 27)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90886', 'locality' => '', 'municipality_id' => Municipality::where('key', 27)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90887', 'locality' => '', 'municipality_id' => Municipality::where('key', 27)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90890', 'locality' => '', 'municipality_id' => Municipality::where('key', 25)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90894', 'locality' => '', 'municipality_id' => Municipality::where('key', 25)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90895', 'locality' => '', 'municipality_id' => Municipality::where('key', 25)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90896', 'locality' => '', 'municipality_id' => Municipality::where('key', 25)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90897', 'locality' => '', 'municipality_id' => Municipality::where('key', 25)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90898', 'locality' => '', 'municipality_id' => Municipality::where('key', 25)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90900', 'locality' => 'Villa Vicente Guerrero', 'municipality_id' => Municipality::where('key', 25)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90920', 'locality' => 'Villa Vicente Guerrero', 'municipality_id' => Municipality::where('key', 25)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90930', 'locality' => 'Villa Vicente Guerrero', 'municipality_id' => Municipality::where('key', 25)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90940', 'locality' => 'Villa Vicente Guerrero', 'municipality_id' => Municipality::where('key', 25)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90950', 'locality' => 'Villa Vicente Guerrero', 'municipality_id' => Municipality::where('key', 25)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90960', 'locality' => 'Villa Vicente Guerrero', 'municipality_id' => Municipality::where('key', 25)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90970', 'locality' => 'Villa Vicente Guerrero', 'municipality_id' => Municipality::where('key', 25)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90980', 'locality' => 'Villa Vicente Guerrero', 'municipality_id' => Municipality::where('key', 25)->where('state_id', 29)->first()->id , 'state_id' => 29],
            [ 'zip_code' => '90990', 'locality' => 'Villa Vicente Guerrero', 'municipality_id' => Municipality::where('key', 25)->where('state_id', 29)->first()->id , 'state_id' => 29],
        ];

        ZipCode::insert($zipCodes);
        unset($zipCodes);
    }
}
